-- =====================================================================================
-- 020_seed_products_part1.sql — Home & Living / Kitchen & Dining / Electronics & Appliances
-- =====================================================================================

-- ===== FURNITURE (home-living) =====
select admin_seed_product('Adjustable 5-Tier Shoe Rack','FUR-01','sinomart-essentials',array['furniture','storage-organization'],'furniture','Space-saving shoe storage for up to 25 pairs.','A powder-coated steel shoe rack with five adjustable-height shelves, designed to fit narrow entryways and hallways. Tool-free assembly and a stable non-slip base.',18500,22000,120,10,'1 Piece','piece',1,'sinomart-fur-01',true,false,false);
select admin_seed_product('3-Seater Fabric Sofa','FUR-02','vono',array['furniture'],'furniture','Comfortable upholstered sofa for living rooms.','A generously padded 3-seater sofa upholstered in durable woven fabric, with solid wood legs and high-density foam cushions that hold their shape.',185000,null,25,5,'1 Piece','piece',1,'sinomart-fur-02',true,false,true);
select admin_seed_product('Round Wooden Center Table','FUR-03','lush-and-home',array['furniture'],'furniture','Compact center table with a warm wood finish.','A round center table with a solid engineered-wood top and tapered legs, sized to fit small and medium living rooms without overwhelming the space.',42000,49500,60,8,'1 Piece','piece',1,'sinomart-fur-03',false,true,false);
select admin_seed_product('4-Tier Bookshelf & Display Unit','FUR-04','lush-and-home',array['furniture','storage-organization'],'furniture','Open-shelf storage for books, decor, and plants.','A freestanding four-tier bookshelf in a walnut-effect finish, offering flexible open storage for books, framed photos, and small decor pieces.',36000,null,45,8,'1 Piece','piece',1,'sinomart-fur-04',false,false,false);
select admin_seed_product('Foldable Study & Office Desk','FUR-05','vono',array['furniture','office-furniture'],'furniture','Compact desk that folds flat for easy storage.','A lightweight foldable desk with a scratch-resistant laminate top, ideal for small bedrooms, home offices, or study corners. Folds flat in seconds.',27500,32000,80,10,'1 Piece','piece',1,'sinomart-fur-05',false,true,false);
select admin_seed_product('Padded Dining Chair (Set of 2)','FUR-06','vono',array['furniture','curtains-home-accessories'],'furniture','Upholstered dining chairs with sturdy metal legs.','A pair of dining chairs with cushioned seats and backrests upholstered in wipeable faux leather, set on powder-coated metal legs for stability.',54000,null,35,6,'1 Set of 2','set',2,'sinomart-fur-06',false,false,false);
select admin_seed_product('6-Drawer Wardrobe Cabinet','FUR-07','vono',array['furniture','bedroom'],'furniture','Freestanding wardrobe with hanging rail and drawers.','A spacious wardrobe combining a full hanging rail with six drawers for folded clothing, finished in an easy-clean matte laminate.',95000,110000,20,4,'1 Piece','piece',1,'sinomart-fur-07',false,false,false);
select admin_seed_product('Rattan-Style Outdoor Patio Chair','FUR-08','lush-and-home',array['furniture'],'furniture','Weather-resistant seating for balconies and patios.','A synthetic rattan-weave chair built on a rust-resistant steel frame, designed to withstand outdoor conditions while staying lightweight to move.',38500,null,50,8,'1 Piece','piece',1,'sinomart-fur-08',false,false,false);
select admin_seed_product('Storage Ottoman Bench','FUR-09','lush-and-home',array['furniture','storage-organization'],'furniture','Cushioned bench that doubles as hidden storage.','A padded ottoman bench with a hinged lid concealing a roomy internal compartment, perfect for hallways, bedrooms, or the foot of a bed.',24000,28000,65,8,'1 Piece','piece',1,'sinomart-fur-09',false,false,false);
select admin_seed_product('3-Tier Corner Shelf Unit','FUR-10','sinomart-essentials',array['furniture','storage-organization'],'furniture','Triangular shelving that makes use of unused corners.','A corner-fit shelving unit in three tiers, ideal for small living rooms or bedrooms where floor space is limited but display storage is needed.',21000,null,55,8,'1 Piece','piece',1,'sinomart-fur-10',false,false,false);

-- ===== HOME DECOR (home-living) =====
select admin_seed_product('Round Wall Clock with Silent Movement','DEC-01','sinomart-essentials',array['home-decor'],'home-decor','30cm wall clock with a non-ticking sweep movement.','A minimalist round wall clock finished in matte black, featuring a silent sweep mechanism so there is no audible ticking in quiet rooms.',8500,10500,150,15,'1 Piece','piece',1,'sinomart-dec-01',false,false,true);
select admin_seed_product('Set of 3 Framed Abstract Wall Art','DEC-02','lush-and-home',array['home-decor'],'home-decor','Canvas prints to instantly refresh a living room wall.','A coordinated set of three framed canvas prints featuring abstract line and colour design, pre-fitted with wall-mounting hardware.',19500,null,70,10,'1 Set of 3','set',3,'sinomart-dec-02',false,true,false);
select admin_seed_product('Woven Storage Basket Set (3 Sizes)','DEC-03','sinomart-essentials',array['home-decor','storage-organization'],'home-decor','Stackable baskets for blankets, toys, or laundry.','A set of three handwoven-style storage baskets in graduated sizes, useful as decorative organizers for throws, magazines, or children''s toys.',15500,18000,90,10,'1 Set of 3','set',3,'sinomart-dec-03',false,false,false);
select admin_seed_product('Ceramic Table Vase (Tall)','DEC-04','lush-and-home',array['home-decor'],'home-decor','Glazed ceramic vase for fresh or artificial flowers.','A tall glazed ceramic vase with a matte exterior finish, wide enough to hold a generous floral arrangement without tipping.',9800,null,110,10,'1 Piece','piece',1,'sinomart-dec-04',false,false,false);
select admin_seed_product('Scented Soy Candle Trio','DEC-05','lush-and-home',array['home-decor','bath-body'],'home-decor','Long-burning soy candles in three signature scents.','Three hand-poured soy wax candles — vanilla, sandalwood, and citrus — each with an approximate 30-hour burn time in a reusable glass jar.',12500,15000,130,15,'1 Set of 3','set',3,'sinomart-dec-05',false,false,false);
select admin_seed_product('Decorative Throw Pillow Covers (Set of 4)','DEC-06','sinomart-essentials',array['home-decor','bedroom'],'home-decor','Mix-and-match covers to refresh sofas and beds.','Four coordinating cushion covers in complementary textures and patterns, sized for standard 45x45cm inserts (inserts sold separately).',9500,null,140,15,'1 Set of 4','set',4,'sinomart-dec-06',false,false,false);
select admin_seed_product('LED String Fairy Lights (10m)','DEC-07','sinomart-essentials',array['home-decor','lighting'],'home-decor','Warm white fairy lights for shelves, mirrors, or plants.','A 10-metre strand of 100 warm-white LED fairy lights, battery or USB powered, ideal for wrapping around mirrors, shelves, or headboards.',6500,8000,200,20,'1 Piece','piece',1,'sinomart-dec-07',false,false,true);
select admin_seed_product('Decorative Wall Mirror (Round)','DEC-08','lush-and-home',array['home-decor'],'home-decor','60cm round mirror with a slim metal frame.','A round wall mirror in a slim gold-tone metal frame, sized to make an entryway or living room feel larger and brighter.',22000,null,45,6,'1 Piece','piece',1,'sinomart-dec-08',false,false,false);
select admin_seed_product('Artificial Potted Plant (Fiddle Leaf)','DEC-09','lush-and-home',array['home-decor'],'home-decor','Realistic faux plant requiring zero maintenance.','A lifelike artificial fiddle-leaf fig in a woven planter pot, offering greenery for spaces with low natural light or busy schedules.',17500,20500,75,10,'1 Piece','piece',1,'sinomart-dec-09',false,false,false);
select admin_seed_product('Table Runner & Placemat Set','DEC-10','sinomart-essentials',array['home-decor','dinnerware'],'home-decor','Coordinated table linen set for six place settings.','A woven table runner paired with six matching placemats, machine-washable and designed to dress up everyday or occasion dining.',11000,null,95,10,'1 Set','set',1,'sinomart-dec-10',false,false,false);

-- ===== COOKWARE (kitchen-dining) =====
select admin_seed_product('Non-Stick Frying Pan 28cm','COK-01','sinomart-essentials',array['cookware'],'cookware','Even-heating frying pan with a durable non-stick coating.','A 28cm aluminium frying pan with a reinforced non-stick coating and a heat-resistant handle, suitable for gas and electric hobs.',9500,11500,180,20,'1 Piece','piece',1,'sinomart-cok-01',false,false,true);
select admin_seed_product('5-Piece Stainless Steel Cooking Pot Set','COK-02','sinomart-essentials',array['cookware'],'cookware','Graduated pot set covering everyday cooking needs.','Five stainless-steel cooking pots in graduated sizes with tempered glass lids and stay-cool handles, covering soups, stews, and sauces.',48000,55000,60,8,'1 Set','set',1,'sinomart-cok-02',true,false,true);
select admin_seed_product('Cast Iron Grill Pan','COK-03','sinomart-essentials',array['cookware'],'cookware','Ridged cast iron pan for indoor grilling.','A pre-seasoned cast iron grill pan with raised ridges that sear meat and vegetables while draining excess fat away from the food.',15500,null,70,8,'1 Piece','piece',1,'sinomart-cok-03',false,false,false);
select admin_seed_product('Pressure Cooker 6L','COK-04','binatone',array['cookware'],'cookware','Fast, fuel-efficient cooking for beans, rice, and stews.','A 6-litre stainless-steel pressure cooker with a locking lid and safety-release valve, cutting cooking time significantly for tough ingredients.',32000,38000,45,6,'1 Piece','piece',1,'sinomart-cok-04',false,false,false);
select admin_seed_product('Non-Stick Wok Pan 32cm','COK-05','sinomart-essentials',array['cookware'],'cookware','Wide wok for stir-fries and large-batch cooking.','A 32cm carbon-steel wok with a non-stick interior and dual carrying handles, ideal for stir-fries, frying, and steaming.',13500,null,65,8,'1 Piece','piece',1,'sinomart-cok-05',false,false,false);
select admin_seed_product('Aluminium Baking & Roasting Tray','COK-06','sinomart-essentials',array['cookware','baking-kitchen-tools'],'cookware','Oven-safe tray for roasting meats and vegetables.','A heavy-gauge aluminium roasting tray with rolled edges for a secure grip, safe for oven use up to high temperatures.',7500,9000,100,10,'1 Piece','piece',1,'sinomart-cok-06',false,false,false);
select admin_seed_product('Non-Stick Saucepan with Lid 20cm','COK-07','sinomart-essentials',array['cookware'],'cookware','Everyday saucepan for sauces, grains, and reheating.','A 20cm non-stick saucepan with a fitted glass lid and heat-resistant handle, sized for single portions or side dishes.',8000,null,140,15,'1 Piece','piece',1,'sinomart-cok-07',false,false,false);
select admin_seed_product('Ceramic-Coated Deep Cooking Pot 30cm','COK-08','sinomart-essentials',array['cookware'],'cookware','Large capacity pot for soups, jollof, and stews.','A 30cm deep pot with a ceramic non-stick coating, built for large-batch Nigerian dishes like jollof rice, egusi, and party stews.',22500,26000,55,8,'1 Piece','piece',1,'sinomart-cok-08',false,false,true);
select admin_seed_product('Silicone Oven Mitts (Pair)','COK-09','sinomart-essentials',array['cookware'],'cookware','Heat-resistant mitts with a textured, non-slip grip.','A pair of quilted silicone oven mitts rated for high heat, with a textured grip surface that stays secure even with damp hands.',3500,null,220,20,'1 Pair','pair',1,'sinomart-cok-09',false,false,false);
select admin_seed_product('Electric Rice Cooker 1.8L','COK-10','binatone',array['cookware','small-kitchen-appliances'],'cookware','One-touch rice cooker with a keep-warm function.','A 1.8-litre electric rice cooker with a non-stick inner pot and automatic keep-warm mode, simplifying daily rice preparation.',18500,21000,90,10,'1 Piece','piece',1,'sinomart-cok-10',false,true,false);

-- ===== LUNCH BOXES & FLASKS (kitchen-dining, cross-listed into kids/office) =====
select admin_seed_product('Kids 3-Tier Lunch Box','LNB-01','chelino',array['lunch-boxes-flasks','school-essentials','school-supplies'],'lunch-boxes-flasks','Leak-resistant, compartmentalised lunch box for school.','A three-tier stackable lunch box with locking clips and silicone seals, keeping different foods separated and leak-resistant for school runs.',6500,8000,160,20,'1 Piece','piece',1,'sinomart-lnb-01',true,true,false);
select admin_seed_product('Insulated Stainless Steel Food Flask 500ml','LNB-02','sinomart-essentials',array['lunch-boxes-flasks','drinkware'],'lunch-boxes-flasks','Keeps meals hot for hours on the go.','A double-wall vacuum-insulated food flask that keeps soups and stews hot for up to 6 hours, with a wide mouth for easy filling and cleaning.',9500,null,120,15,'1 Piece','piece',1,'sinomart-lnb-02',false,false,false);
select admin_seed_product('Bento-Style Adult Lunch Box with Cutlery','LNB-03','sinomart-essentials',array['lunch-boxes-flasks'],'lunch-boxes-flasks','Portion-controlled lunch box for office meals.','A two-compartment bento lunch box with a built-in cutlery set, designed for portion-controlled office or gym-bag meals.',7500,9000,110,15,'1 Piece','piece',1,'sinomart-lnb-03',false,false,false);
select admin_seed_product('1.5L Stainless Steel Vacuum Water Bottle','LNB-04','sinomart-essentials',array['lunch-boxes-flasks','drinkware'],'lunch-boxes-flasks','Large-capacity insulated bottle for all-day hydration.','A 1.5-litre double-wall stainless steel bottle that keeps water cold for up to 24 hours, with a leak-proof flip lid and carry handle.',11500,13500,95,10,'1 Piece','piece',1,'sinomart-lnb-04',true,false,true);
select admin_seed_product('Children''s Sipper Water Bottle 350ml','LNB-05','chelino',array['lunch-boxes-flasks','baby-accessories'],'lunch-boxes-flasks','Spill-proof bottle sized for small hands.','A lightweight 350ml sipper bottle with a spill-proof straw lid, sized and shaped for young children to hold and drink from independently.',3200,null,180,20,'1 Piece','piece',1,'sinomart-lnb-05',false,false,false);
select admin_seed_product('Vacuum Flask 1L with Cup Lid','LNB-06','sinomart-essentials',array['lunch-boxes-flasks'],'lunch-boxes-flasks','Classic vacuum flask for tea, coffee, or pap.','A 1-litre glass-lined vacuum flask with a cup-style lid, keeping hot beverages warm for hours — a household staple across Nigeria.',7000,8500,150,15,'1 Piece','piece',1,'sinomart-lnb-06',false,false,true);
select admin_seed_product('Leak-Proof Salad Container with Fork','LNB-07','sinomart-essentials',array['lunch-boxes-flasks'],'lunch-boxes-flasks','Compartmentalised container to keep dressing separate.','A round salad container with a separate small compartment for dressing and a clip-in fork, keeping greens crisp until lunchtime.',5000,null,130,15,'1 Piece','piece',1,'sinomart-lnb-07',false,false,false);
select admin_seed_product('Double-Decker Steel Tiffin Carrier','LNB-08','sinomart-essentials',array['lunch-boxes-flasks'],'lunch-boxes-flasks','Traditional stacked tiffin for transporting full meals.','A two-tier stainless-steel tiffin carrier with a secure locking handle, well suited to carrying rice-and-stew combinations to work or school.',8500,10000,85,10,'1 Piece','piece',1,'sinomart-lnb-08',false,false,false);
select admin_seed_product('Insulated Lunch Bag with Bottle Sleeve','LNB-09','sinomart-essentials',array['lunch-boxes-flasks','bags-backpacks'],'lunch-boxes-flasks','Padded carry bag that keeps lunch boxes cool.','An insulated fabric lunch bag with a zip closure and a side sleeve for a water bottle, sized to fit most lunch boxes on this list.',5500,null,140,15,'1 Piece','piece',1,'sinomart-lnb-09',false,false,false);
select admin_seed_product('Glass Flask with Tea Infuser 480ml','LNB-10','sinomart-essentials',array['lunch-boxes-flasks','drinkware'],'lunch-boxes-flasks','Borosilicate glass flask with a removable infuser.','A borosilicate glass flask with a stainless-steel infuser basket, letting loose-leaf tea or fruit infuse while staying protected in a sleeve.',9000,null,75,10,'1 Piece','piece',1,'sinomart-lnb-10',false,true,false);

-- ===== DRINKWARE (kitchen-dining) =====
select admin_seed_product('6-Piece Ceramic Mug Set','DRK-01','sinomart-essentials',array['drinkware'],'drinkware','Everyday mugs for coffee, tea, and cocoa.','A set of six glazed ceramic mugs in a rounded design, dishwasher and microwave safe, sized for a generous cup of coffee or tea.',9500,null,220,20,'1 Set of 6','set',6,'sinomart-drk-01',true,false,true);
select admin_seed_product('Frosted Glass Tumbler Set (4 Pieces)','DRK-02','sinomart-essentials',array['drinkware'],'drinkware','Sturdy tumblers for water, juice, or soft drinks.','Four frosted-finish glass tumblers with a comfortable weighted base, resistant to everyday chips and scratches.',6000,7500,190,20,'1 Set of 4','set',4,'sinomart-drk-02',false,false,false);
select admin_seed_product('Insulated Travel Coffee Mug 450ml','DRK-03','sinomart-essentials',array['drinkware'],'drinkware','Spill-proof mug that keeps coffee hot on commutes.','A double-wall insulated travel mug with a locking spill-proof lid and a fitted car-cup-holder base.',7200,null,130,15,'1 Piece','piece',1,'sinomart-drk-03',false,false,false);
select admin_seed_product('Crystal-Cut Wine Glasses (Set of 6)','DRK-04','lush-and-home',array['drinkware'],'drinkware','Elegant glassware for entertaining guests.','Six crystal-cut stemmed wine glasses with a classic tulip shape, suited to both everyday dinners and special occasions.',13500,16000,80,10,'1 Set of 6','set',6,'sinomart-drk-04',false,false,false);
select admin_seed_product('Plastic Water Jug with Lid 2.5L','DRK-05','sinomart-essentials',array['drinkware'],'drinkware','Durable BPA-free jug for the fridge or dining table.','A 2.5-litre BPA-free plastic jug with a snap-fit lid and wide handle, sized to fit most fridge doors.',3500,null,240,20,'1 Piece','piece',1,'sinomart-drk-05',false,false,false);
select admin_seed_product('Stainless Steel Hip Flask 200ml','DRK-06','sinomart-essentials',array['drinkware'],'drinkware','Compact flask for travel or gifting.','A pocket-sized stainless-steel flask with a screw cap and funnel included, popular as a practical gift item.',4500,5500,90,10,'1 Piece','piece',1,'sinomart-drk-06',false,false,false);
select admin_seed_product('Espresso Cup & Saucer Set (Set of 4)','DRK-07','sinomart-essentials',array['drinkware'],'drinkware','Small-format cups for espresso or short coffee.','Four ceramic espresso cups with matching saucers, sized for concentrated coffee servings and finished in a glossy white glaze.',7000,null,100,10,'1 Set of 4','set',4,'sinomart-drk-07',false,false,false);
select admin_seed_product('Kids Character Sipper Cups (Set of 2)','DRK-08','chelino',array['drinkware','kids-fashion'],'drinkware','Fun, spill-resistant cups for younger children.','Two BPA-free sipper cups with soft silicone spouts, designed to encourage independent drinking for toddlers and young children.',4800,null,150,15,'1 Set of 2','set',2,'sinomart-drk-08',false,false,false);
select admin_seed_product('Copper Finish Moscow Mule Mugs (Set of 2)','DRK-09','lush-and-home',array['drinkware'],'drinkware','Statement mugs for cocktails and cold drinks.','A pair of copper-finished stainless-steel mugs, ideal for chilled cocktails or simply as a decorative drinkware accent.',9500,11000,60,8,'1 Set of 2','set',2,'sinomart-drk-09',false,false,false);
select admin_seed_product('Reusable Plastic Cups (Pack of 12)','DRK-10','sinomart-essentials',array['drinkware'],'drinkware','Party-ready cups for indoor or outdoor gatherings.','Twelve stackable, reusable plastic cups suited to parties, picnics, and everyday household use.',4000,null,200,20,'1 Pack of 12','pack',12,'sinomart-drk-10',false,false,false);
