-- =====================================================================================
-- 021_seed_products_part2.sql — Electronics & Appliances: Televisions / Fans / Gadgets & Accessories
-- =====================================================================================

-- ===== TELEVISIONS (electronics-appliances) =====
select admin_seed_product('32" HD LED Television','TVE-01','hisense',array['televisions'],'televisions','Compact HD television for bedrooms and kitchens.','A 32-inch LED television with HD resolution, built-in digital tuner, and multiple HDMI/USB ports for external devices.',95000,110000,40,5,'1 Piece','piece',1,'sinomart-tve-01',true,false,true);
select admin_seed_product('43" Full HD Smart LED TV','TVE-02','hisense',array['televisions'],'televisions','Smart TV with built-in streaming apps.','A 43-inch Full HD smart television with pre-installed streaming apps, Wi-Fi connectivity, and a slim bezel design.',165000,185000,30,5,'1 Piece','piece',1,'sinomart-tve-02',true,false,true);
select admin_seed_product('50" 4K UHD Smart Television','TVE-03','samsung',array['televisions'],'televisions','Crisp 4K picture with smart streaming features.','A 50-inch 4K Ultra HD smart television delivering sharp detail and vivid colour, with app support for major streaming platforms.',285000,320000,18,4,'1 Piece','piece',1,'sinomart-tve-03',true,false,false);
select admin_seed_product('55" 4K UHD Smart Television','TVE-04','lg',array['televisions'],'televisions','Large-format 4K display for living rooms.','A 55-inch 4K UHD television with HDR support and a slim-profile stand, suited to larger living rooms and home entertainment setups.',345000,null,15,3,'1 Piece','piece',1,'sinomart-tve-04',false,false,false);
select admin_seed_product('24" LED TV with Built-In DVD Player','TVE-05','hisense',array['televisions'],'televisions','Compact all-in-one TV/DVD combo unit.','A 24-inch LED television with an integrated DVD player, well suited to small rooms, offices, or as a secondary television.',58000,null,50,6,'1 Piece','piece',1,'sinomart-tve-05',false,false,false);
select admin_seed_product('65" 4K Smart TV with Voice Remote','TVE-06','samsung',array['televisions'],'televisions','Premium large-screen viewing experience.','A 65-inch 4K smart television with a voice-enabled remote, multiple HDMI 2.1 ports, and support for major streaming and gaming devices.',475000,520000,8,3,'1 Piece','piece',1,'sinomart-tve-06',true,false,false);
select admin_seed_product('40" Full HD LED TV','TVE-07','lg',array['televisions'],'televisions','Balanced size and picture quality for everyday use.','A 40-inch Full HD LED television offering a practical balance of screen size and price for everyday household viewing.',135000,null,32,5,'1 Piece','piece',1,'sinomart-tve-07',false,false,false);
select admin_seed_product('Wall Mount Bracket for TVs 32"-65"','TVE-08','sinomart-essentials',array['televisions'],'televisions','Adjustable tilt mount for most flat-screen TVs.','A universal tilting wall mount compatible with most 32-inch to 65-inch televisions, sold with mounting hardware and an instruction guide.',12500,15000,90,10,'1 Piece','piece',1,'sinomart-tve-08',false,false,false);
select admin_seed_product('32" LED TV with Satellite Tuner','TVE-09','hisense',array['televisions'],'televisions','Built-in tuner for local satellite reception.','A 32-inch LED television with an integrated satellite tuner, removing the need for a separate decoder for local free-to-air channels.',98000,null,35,5,'1 Piece','piece',1,'sinomart-tve-09',false,false,false);
select admin_seed_product('Portable Mini LED TV 19"','TVE-10','hisense',array['televisions'],'televisions','Small-format TV for kitchens or dorm rooms.','A compact 19-inch LED television, lightweight enough to move between rooms, with a built-in stand and remote control.',42000,48000,55,8,'1 Piece','piece',1,'sinomart-tve-10',false,false,false);

-- ===== FANS (electronics-appliances) =====
select admin_seed_product('Portable Rechargeable Standing Fan','FAN-01','binatone',array['fans'],'fans','Battery-backed fan for use during power outages.','A rechargeable standing fan with a built-in battery offering several hours of runtime, three speed settings, and an oscillating head.',28500,34000,75,10,'1 Piece','piece',1,'sinomart-fan-01',true,true,true);
select admin_seed_product('16" Industrial Standing Fan','FAN-02','binatone',array['fans'],'fans','High-powered fan for large rooms or shops.','A 16-inch industrial-grade standing fan with a metal blade and heavy base, built for strong, continuous airflow in larger spaces.',32000,null,45,6,'1 Piece','piece',1,'sinomart-fan-02',false,false,false);
select admin_seed_product('Desk Fan with Adjustable Tilt','FAN-03','binatone',array['fans'],'fans','Compact fan for desks and bedside tables.','A small desk fan with a tilting head and quiet operation, sized to sit comfortably on a work desk or bedside table.',7500,9000,150,15,'1 Piece','piece',1,'sinomart-fan-03',false,false,false);
select admin_seed_product('Rechargeable Table Fan with LED Light','FAN-04','binatone',array['fans','lighting'],'fans','Dual-purpose fan and emergency light.','A rechargeable table fan combined with an LED lighting panel, useful for both cooling and emergency lighting during outages.',15500,18000,95,10,'1 Piece','piece',1,'sinomart-fan-04',false,true,false);
select admin_seed_product('Wall-Mounted Oscillating Fan','FAN-05','binatone',array['fans'],'fans','Space-saving fan that mounts directly to the wall.','A wall-mounted fan with a remote control and oscillating function, freeing up floor space in kitchens, shops, or small rooms.',22000,null,60,8,'1 Piece','piece',1,'sinomart-fan-05',false,false,false);
select admin_seed_product('Rechargeable Mini Handheld Fan','FAN-06','sinomart-essentials',array['fans'],'fans','Pocket-sized personal cooling fan.','A USB-rechargeable handheld fan with a folding handle, small enough to carry in a bag for personal cooling on the move.',4500,5500,180,15,'1 Piece','piece',1,'sinomart-fan-06',false,false,true);
select admin_seed_product('Ceiling Fan with Light Kit 56"','FAN-07','binatone',array['fans','lighting'],'fans','Combined ceiling fan and light fixture.','A 56-inch ceiling fan with an integrated LED light kit and reversible motor for both cooling and warm-air circulation seasons.',45000,52000,25,5,'1 Piece','piece',1,'sinomart-fan-07',false,false,false);
select admin_seed_product('18" Rechargeable Standing Fan with Remote','FAN-08','binatone',array['fans'],'fans','Larger rechargeable fan with full remote control.','An 18-inch rechargeable standing fan with a long-life battery, remote control, and timer function for scheduled cooling.',38000,null,40,6,'1 Piece','piece',1,'sinomart-fan-08',true,false,false);
select admin_seed_product('Clip-On Fan for Cots and Prams','FAN-09','chelino',array['fans','baby-accessories'],'fans','Gentle airflow fan designed for babies.','A small clip-on fan with soft blades and quiet operation, designed to attach securely to a cot, pram, or car seat.',5500,null,110,10,'1 Piece','piece',1,'sinomart-fan-09',false,false,false);
select admin_seed_product('USB Desktop Cooling Fan','FAN-10','sinomart-essentials',array['fans','gadgets-accessories'],'fans','Compact fan powered directly by USB.','A small USB-powered desktop fan with flexible positioning, ideal for laptops, PCs, or any USB-powered setup.',3200,4000,200,20,'1 Piece','piece',1,'sinomart-fan-10',false,false,false);

-- ===== GADGETS & ACCESSORIES (electronics-appliances) =====
select admin_seed_product('20000mAh Fast-Charging Power Bank','GAD-01','anker',array['gadgets-accessories'],'gadgets-accessories','High-capacity power bank for multiple full charges.','A 20,000mAh power bank with dual USB outputs and fast-charging support, capable of fully charging most smartphones several times over.',18500,22000,140,15,'1 Piece','piece',1,'sinomart-gad-01',true,false,true);
select admin_seed_product('Bluetooth Wireless Earbuds','GAD-02','tecno',array['gadgets-accessories','audio'],'gadgets-accessories','True wireless earbuds with a charging case.','A pair of Bluetooth 5.0 wireless earbuds with a compact charging case, touch controls, and several hours of continuous playback.',15500,19000,160,15,'1 Piece','piece',1,'sinomart-gad-02',true,true,true);
select admin_seed_product('Portable Bluetooth Speaker','GAD-03','anker',array['gadgets-accessories','audio'],'gadgets-accessories','Compact speaker with rich bass for outdoor use.','A rugged, splash-resistant Bluetooth speaker delivering surprisingly rich bass for its size, with a long-lasting rechargeable battery.',21500,25000,85,10,'1 Piece','piece',1,'sinomart-gad-03',false,false,true);
select admin_seed_product('Universal Fast Wall Charger (Dual USB)','GAD-04','anker',array['gadgets-accessories'],'gadgets-accessories','Compact charger with two fast-charging ports.','A compact wall charger with two USB output ports supporting fast charging for phones and tablets simultaneously.',5500,null,220,20,'1 Piece','piece',1,'sinomart-gad-04',false,false,false);
select admin_seed_product('Smartwatch with Fitness Tracking','GAD-05','tecno',array['gadgets-accessories'],'gadgets-accessories','Track steps, heart rate, and notifications.','A smartwatch with a colour touchscreen, heart-rate and step tracking, and smartphone notification mirroring, paired via Bluetooth.',24500,29000,70,8,'1 Piece','piece',1,'sinomart-gad-05',true,false,false);
select admin_seed_product('USB-C to USB-C Charging Cable 1.2m','GAD-06','anker',array['gadgets-accessories'],'gadgets-accessories','Durable braided cable for fast charging.','A 1.2-metre braided USB-C to USB-C cable rated for fast charging and reliable data transfer, resistant to everyday fraying.',3500,null,260,20,'1 Piece','piece',1,'sinomart-gad-06',false,false,false);
select admin_seed_product('Ring Light with Phone Holder 10"','GAD-07','sinomart-essentials',array['gadgets-accessories'],'gadgets-accessories','LED ring light for video calls and content creation.','A 10-inch LED ring light on an adjustable tripod stand with a phone clip, offering three brightness modes for calls, streaming, or photos.',12500,15000,90,10,'1 Piece','piece',1,'sinomart-gad-07',false,true,false);
select admin_seed_product('Wireless Charging Pad','GAD-08','anker',array['gadgets-accessories'],'gadgets-accessories','Cable-free charging for compatible phones.','A slim Qi-certified wireless charging pad, letting compatible phones charge simply by resting on the surface — no cable required.',9500,11500,120,12,'1 Piece','piece',1,'sinomart-gad-08',false,false,false);
select admin_seed_product('Car Phone Mount (Dashboard/Vent)','GAD-09','sinomart-essentials',array['gadgets-accessories'],'gadgets-accessories','Secure phone mount for hands-free navigation.','A dashboard and air-vent compatible phone mount with a spring-loaded grip, keeping phones secure and visible while driving.',4500,null,170,15,'1 Piece','piece',1,'sinomart-gad-09',false,false,false);
select admin_seed_product('Bluetooth Selfie Stick with Tripod','GAD-10','sinomart-essentials',array['gadgets-accessories'],'gadgets-accessories','Extendable stick that doubles as a tripod.','An extendable selfie stick with a detachable Bluetooth remote and folding tripod legs, suited for both photos and steady video.',6500,8000,150,15,'1 Piece','piece',1,'sinomart-gad-10',false,false,false);
