-- =====================================================================================
-- 022_seed_products_part3.sql — Fashion & Accessories: Footwear / Jewellery
--                                Beauty & Personal Care: Face Care / Skincare
-- =====================================================================================

-- ===== FOOTWEAR (fashion-accessories) =====
select admin_seed_product('Women''s Casual Platform Slides','FTW-01','sinomart-essentials',array['footwear'],'footwear','Everyday slides with a comfort platform sole.','A pair of women''s platform slides in a soft synthetic upper, offering a comfortable everyday sole with light cushioning.',8500,10500,140,15,'1 Pair','pair',1,'sinomart-ftw-01',true,true,true);
select admin_seed_product('Classic Clog Sandals (Unisex)','FTW-02','crocs',array['footwear'],'footwear','Lightweight, water-friendly clog sandals.','A pair of lightweight foam clog sandals with ventilation holes and a heel strap, easy to clean and suited to indoor or outdoor wear.',22000,null,95,10,'1 Pair','pair',1,'sinomart-ftw-02',false,false,true);
select admin_seed_product('Men''s Running Sneakers','FTW-03','adidas',array['footwear'],'footwear','Cushioned sneakers for training and daily wear.','A pair of men''s running sneakers with a breathable mesh upper and cushioned midsole, suited to training sessions or everyday errands.',38500,45000,60,8,'1 Pair','pair',1,'sinomart-ftw-03',true,false,false);
select admin_seed_product('Women''s Ballet Flats','FTW-04','sinomart-essentials',array['footwear'],'footwear','Comfortable flats for office or casual wear.','A pair of women''s ballet flats in a soft PU upper with a padded insole, versatile enough for office wear or casual outings.',9500,null,110,10,'1 Pair','pair',1,'sinomart-ftw-04',false,false,false);
select admin_seed_product('Kids Velcro Sneakers','FTW-05','sinomart-essentials',array['footwear','kids-fashion'],'footwear','Easy-fasten sneakers for younger children.','A pair of kids'' sneakers with a double velcro strap closure, making them easy for children to put on and take off independently.',7500,9000,130,12,'1 Pair','pair',1,'sinomart-ftw-05',false,false,false);
select admin_seed_product('Men''s Leather Loafers','FTW-06','sinomart-essentials',array['footwear'],'footwear','Smart-casual loafers for office and events.','A pair of men''s slip-on loafers in a smooth leather-effect upper, suited to office wear or smart-casual occasions.',16500,19500,70,8,'1 Pair','pair',1,'sinomart-ftw-06',false,false,false);
select admin_seed_product('Women''s Wedge Heel Sandals','FTW-07','sinomart-essentials',array['footwear'],'footwear','Elevated sandals with all-day wearable comfort.','A pair of women''s wedge sandals with an ankle strap and cushioned footbed, balancing height with practical all-day comfort.',13500,null,75,10,'1 Pair','pair',1,'sinomart-ftw-07',false,false,false);
select admin_seed_product('Sports Slides with Adjustable Strap','FTW-08','nike',array['footwear'],'footwear','Post-workout recovery slides.','A pair of sports slides with an adjustable strap and contoured footbed, popular for post-gym or post-run recovery wear.',14500,17000,100,10,'1 Pair','pair',1,'sinomart-ftw-08',false,false,false);
select admin_seed_product('Men''s Ankle Boots','FTW-09','sinomart-essentials',array['footwear'],'footwear','Durable boots for rugged everyday wear.','A pair of men''s ankle boots in a durable synthetic-leather upper with a grippy rubber sole, built for daily wear and light outdoor use.',21500,25000,55,8,'1 Pair','pair',1,'sinomart-ftw-09',false,false,false);
select admin_seed_product('Rain Boots (Unisex, Mid-Calf)','FTW-10','sinomart-essentials',array['footwear'],'footwear','Waterproof boots for rainy-season commutes.','A pair of mid-calf rubber rain boots with a textured non-slip sole, well suited to Lagos rainy-season commuting.',9500,null,85,10,'1 Pair','pair',1,'sinomart-ftw-10',false,false,false);

-- ===== JEWELLERY (fashion-accessories) =====
select admin_seed_product('Gold-Plated Layered Necklace','JWL-01','sinomart-essentials',array['jewellery'],'jewellery','Delicate layered necklace for everyday wear.','An 18k gold-plated layered necklace with two chain lengths, designed to sit together for a subtle stacked look.',6500,8000,150,15,'1 Piece','piece',1,'sinomart-jwl-01',true,true,false);
select admin_seed_product('Stainless Steel Cuff Bracelet','JWL-02','sinomart-essentials',array['jewellery'],'jewellery','Adjustable cuff bracelet, tarnish resistant.','An open-cuff bracelet in brushed stainless steel, adjustable to fit most wrist sizes and resistant to everyday tarnishing.',5500,null,130,12,'1 Piece','piece',1,'sinomart-jwl-02',false,false,false);
select admin_seed_product('Pearl Stud Earrings','JWL-03','sinomart-essentials',array['jewellery'],'jewellery','Classic pearl studs for everyday elegance.','A pair of freshwater pearl stud earrings on hypoallergenic posts, a versatile everyday accessory for work or occasions.',4500,5500,180,15,'1 Pair','pair',1,'sinomart-jwl-03',false,false,true);
select admin_seed_product('Beaded Statement Necklace','JWL-04','sinomart-essentials',array['jewellery'],'jewellery','Bold beaded necklace for occasion wear.','A chunky beaded statement necklace in a warm colour palette, designed to be the focal point of an outfit.',7500,null,95,10,'1 Piece','piece',1,'sinomart-jwl-04',false,false,false);
select admin_seed_product('Men''s Stainless Steel Chain Bracelet','JWL-05','sinomart-essentials',array['jewellery'],'jewellery','Sturdy chain bracelet for daily wear.','A men''s curb-link bracelet in brushed stainless steel with a secure fold-over clasp, built for daily wear.',6000,7200,100,10,'1 Piece','piece',1,'sinomart-jwl-05',false,false,false);
select admin_seed_product('Gold-Plated Hoop Earrings (Set of 3)','JWL-06','sinomart-essentials',array['jewellery'],'jewellery','Three hoop sizes for mix-and-match styling.','A set of three gold-plated hoop earrings in small, medium, and large sizes, letting you switch styles without buying separately.',5800,null,140,12,'1 Set of 3','set',3,'sinomart-jwl-06',false,true,false);
select admin_seed_product('Charm Pendant Necklace','JWL-07','sinomart-essentials',array['jewellery'],'jewellery','Personal-touch pendant on a fine chain.','A fine-chain necklace with a small decorative charm pendant, a popular gifting choice for birthdays and anniversaries.',4800,5800,120,10,'1 Piece','piece',1,'sinomart-jwl-07',false,false,false);
select admin_seed_product('Adjustable Signet Ring','JWL-08','sinomart-essentials',array['jewellery'],'jewellery','Classic signet-style ring, one size fits most.','A gold-tone signet ring with an open adjustable band, comfortably fitting a range of finger sizes.',3800,null,160,15,'1 Piece','piece',1,'sinomart-jwl-08',false,false,false);
select admin_seed_product('Crystal Drop Earrings','JWL-09','sinomart-essentials',array['jewellery'],'jewellery','Sparkling drop earrings for evening wear.','A pair of crystal-embellished drop earrings, catching the light for evening events, parties, or formal occasions.',6200,7500,85,10,'1 Pair','pair',1,'sinomart-jwl-09',false,false,false);
select admin_seed_product('Beaded Anklet Set (Set of 2)','JWL-10','sinomart-essentials',array['jewellery'],'jewellery','Lightweight anklets for warm-weather styling.','Two coordinating beaded anklets with an adjustable extender chain, a lightweight accessory for sandals and warm-weather outfits.',3500,null,110,10,'1 Set of 2','set',2,'sinomart-jwl-10',false,false,false);

-- ===== FACE CARE (beauty-personal-care) =====
select admin_seed_product('Gentle Foaming Facial Cleanser 150ml','FCR-01','nivea',array['face-care'],'face-care','Daily cleanser suited to normal-to-dry skin.','A soap-free foaming cleanser that removes dirt and makeup while maintaining the skin''s natural moisture balance, suited to daily use.',4200,5000,200,20,'1 Piece','piece',1,'sinomart-fcr-01',true,false,true);
select admin_seed_product('Vitamin C Brightening Serum 30ml','FCR-02','skinlite',array['face-care','skincare'],'face-care','Antioxidant serum to even out skin tone.','A lightweight vitamin C serum formulated to target uneven tone and dullness, absorbing quickly without a greasy residue.',8500,10500,140,15,'1 Piece','piece',1,'sinomart-fcr-02',true,true,true);
select admin_seed_product('Oil-Free Moisturizer for Combination Skin 100ml','FCR-03','nivea',array['face-care'],'face-care','Lightweight hydration without excess shine.','A gel-based, oil-free moisturizer that hydrates without adding shine, formulated for combination and oily skin types.',5200,null,175,18,'1 Piece','piece',1,'sinomart-fcr-03',false,false,false);
select admin_seed_product('SPF 50 Daily Sunscreen 75ml','FCR-04','nivea',array['face-care'],'face-care','Broad-spectrum sun protection for daily wear.','A broad-spectrum SPF 50 facial sunscreen with a lightweight, non-greasy finish suitable for daily wear under makeup.',6500,7800,190,18,'1 Piece','piece',1,'sinomart-fcr-04',true,false,true);
select admin_seed_product('Clay Detox Face Mask 100g','FCR-05','skinlite',array['face-care'],'face-care','Weekly clay mask to draw out impurities.','A mineral clay mask designed for weekly use, drawing out excess oil and impurities while leaving skin feeling refreshed.',4800,null,120,12,'1 Piece','piece',1,'sinomart-fcr-05',false,false,false);
select admin_seed_product('Hydrating Facial Toner 200ml','FCR-06','nivea',array['face-care'],'face-care','Alcohol-free toner to prep skin after cleansing.','An alcohol-free toner that gently rebalances the skin after cleansing, prepping it to better absorb serums and moisturizers.',4500,5400,150,15,'1 Piece','piece',1,'sinomart-fcr-06',false,false,false);
select admin_seed_product('Micellar Cleansing Water 400ml','FCR-07','nivea',array['face-care'],'face-care','No-rinse makeup remover for sensitive skin.','A gentle micellar water that lifts makeup and impurities in one swipe, formulated for sensitive skin and requiring no rinsing.',5800,null,160,15,'1 Piece','piece',1,'sinomart-fcr-07',false,false,true);
select admin_seed_product('Exfoliating Face Scrub 100ml','FCR-08','zaron',array['face-care'],'face-care','Fine-grain scrub for smoother-feeling skin.','A fine-grain exfoliating scrub that lifts away dead skin cells, formulated to avoid over-stripping natural oils.',4000,4800,135,12,'1 Piece','piece',1,'sinomart-fcr-08',false,false,false);
select admin_seed_product('Under-Eye Gel Patches (Pack of 5 Pairs)','FCR-09','skinlite',array['face-care'],'face-care','Cooling patches to refresh tired eyes.','Five pairs of hydrogel under-eye patches infused with soothing ingredients, designed for a quick refresh before events.',5500,null,100,10,'1 Pack of 5','pack',5,'sinomart-fcr-09',false,true,false);
select admin_seed_product('Rose Water Facial Mist 200ml','FCR-10','skinlite',array['face-care'],'face-care','Refreshing mist for on-the-go hydration.','A pure rose water facial mist that can be used throughout the day to refresh and lightly hydrate the skin over makeup.',3800,null,145,15,'1 Piece','piece',1,'sinomart-fcr-10',false,false,false);

-- ===== SKINCARE (beauty-personal-care) =====
select admin_seed_product('Hyaluronic Acid Hydrating Serum 30ml','SKC-01','skinlite',array['skincare'],'skincare','Lightweight serum for deep hydration.','A hyaluronic-acid serum that draws moisture into the skin, leaving it visibly plumper and more hydrated after regular use.',7500,9000,150,15,'1 Piece','piece',1,'sinomart-skc-01',true,true,true);
select admin_seed_product('Body Lotion with Cocoa Butter 400ml','SKC-02','nivea',array['skincare','bath-body'],'skincare','Rich, fast-absorbing lotion for dry skin.','A cocoa-butter enriched body lotion that absorbs quickly while leaving skin feeling soft for up to 24 hours.',4500,5200,220,20,'1 Piece','piece',1,'sinomart-skc-02',false,false,true);
select admin_seed_product('Bio-Oil Skincare Oil 60ml','SKC-03','bio-oil',array['skincare'],'skincare','Multi-purpose oil for scars and stretch marks.','A specialist skincare oil formulated to help improve the appearance of scars, stretch marks, and uneven skin tone with regular use.',9800,11500,130,12,'1 Piece','piece',1,'sinomart-skc-03',true,false,true);
select admin_seed_product('Shea Butter Body Cream 250ml','SKC-04','sinomart-essentials',array['skincare','bath-body'],'skincare','Deep-moisture cream for very dry skin.','A thick, whipped shea-butter body cream aimed at very dry or rough skin, particularly effective on elbows, knees, and heels.',4200,null,190,18,'1 Piece','piece',1,'sinomart-skc-04',false,false,false);
select admin_seed_product('Retinol Night Repair Cream 50ml','SKC-05','skinlite',array['skincare'],'skincare','Overnight cream targeting fine lines.','A retinol-infused night cream formulated to support skin renewal overnight, aimed at fine lines and uneven texture.',9500,11200,90,10,'1 Piece','piece',1,'sinomart-skc-05',false,false,false);
select admin_seed_product('Niacinamide Serum for Blemish-Prone Skin 30ml','SKC-06','skinlite',array['skincare'],'skincare','Serum to help balance oily, blemish-prone skin.','A niacinamide serum formulated to help visibly reduce the appearance of blemishes and refine the look of pores over time.',7200,null,140,14,'1 Piece','piece',1,'sinomart-skc-06',false,true,false);
select admin_seed_product('Exfoliating Body Scrub with Coffee 300g','SKC-07','sinomart-essentials',array['skincare','bath-body'],'skincare','Invigorating scrub for smoother-feeling skin.','A coffee-ground body scrub that buffs away rough patches, leaving skin feeling smoother and more refreshed after each shower.',3800,4500,160,15,'1 Piece','piece',1,'sinomart-skc-07',false,false,false);
select admin_seed_product('SPF 30 Body Sunscreen Lotion 200ml','SKC-08','nivea',array['skincare'],'skincare','Broad-spectrum body sunscreen for daily wear.','A broad-spectrum SPF 30 body lotion offering daily sun protection with a lightweight, fast-absorbing finish.',6500,null,120,12,'1 Piece','piece',1,'sinomart-skc-08',false,false,false);
select admin_seed_product('Anti-Ageing Eye Cream 20ml','SKC-09','skinlite',array['skincare'],'skincare','Targeted cream for fine lines around the eyes.','A concentrated eye cream targeting fine lines and puffiness, formulated for the delicate skin around the eye area.',8200,9800,75,8,'1 Piece','piece',1,'sinomart-skc-09',false,false,false);
select admin_seed_product('Aloe Vera Soothing Gel 300ml','SKC-10','sinomart-essentials',array['skincare'],'skincare','Multi-use cooling gel for skin and sun relief.','A lightweight aloe vera gel that soothes irritated or sun-exposed skin and can double as a light daily moisturizer.',3500,null,175,15,'1 Piece','piece',1,'sinomart-skc-10',false,false,true);
