-- =====================================================================================
-- 023_seed_products_part4.sql — Kids, Baby & Toys: Toys / School Essentials
--                                Sports & Outdoor: Skates
--                                Office & School: School Supplies
-- =====================================================================================

-- ===== TOYS (kids-baby-toys) =====
select admin_seed_product('120-Piece Building Blocks Set','TOY-01','toyzone',array['toys','educational-toys'],'toys','Colourful interlocking blocks for open-ended play.','A 120-piece interlocking building block set compatible with most major block brands, encouraging creativity and fine motor skills.',9500,11500,150,15,'1 Set','set',1,'sinomart-toy-01',true,true,true);
select admin_seed_product('Remote Control Racing Car','TOY-02','toyzone',array['toys'],'toys','Fast RC car with rechargeable battery.','A remote-controlled racing car with rechargeable battery pack, responsive steering, and durable wheels for indoor or outdoor play.',14500,17500,90,10,'1 Piece','piece',1,'sinomart-toy-02',true,false,true);
select admin_seed_product('Wooden Shape Sorter Puzzle','TOY-03','toyzone',array['toys','educational-toys'],'toys','Classic shape-matching puzzle for toddlers.','A wooden shape-sorting puzzle with chunky, easy-grip pieces, designed to build early problem-solving and coordination skills.',6500,null,130,12,'1 Piece','piece',1,'sinomart-toy-03',false,false,false);
select admin_seed_product('Die-Cast Toy Car Set (Pack of 5)','TOY-04','toyzone',array['toys'],'toys','Miniature die-cast cars for imaginative play.','Five miniature die-cast toy cars in varied designs and colours, built with sturdy metal bodies to withstand rough play.',5500,6800,170,15,'1 Pack of 5','pack',5,'sinomart-toy-04',false,false,false);
select admin_seed_product('Kids Play Kitchen Set','TOY-05','toyzone',array['toys'],'toys','Pretend-play kitchen with accessories.','A compact pretend-play kitchen set including a stove, sink, and utensil accessories, encouraging imaginative role play.',22500,26000,55,8,'1 Set','set',1,'sinomart-toy-05',true,false,false);
select admin_seed_product('500-Piece Jigsaw Puzzle (Landscape)','TOY-06','toyzone',array['toys'],'toys','Family-friendly puzzle for a relaxing activity.','A 500-piece jigsaw puzzle featuring a scenic landscape design, suited to family puzzle nights or quiet solo activity.',6000,null,110,10,'1 Piece','piece',1,'sinomart-toy-06',false,false,false);
select admin_seed_product('Toy Doctor Play Set','TOY-07','toyzone',array['toys'],'toys','Pretend medical kit for imaginative play.','A pretend-play doctor''s kit with a carry case and toy instruments, encouraging role play and early social skills.',7500,9000,95,10,'1 Set','set',1,'sinomart-toy-07',false,false,false);
select admin_seed_product('Spinning Top Battle Set','TOY-08','toyzone',array['toys'],'toys','Competitive spinning top toy set with arena.','A spinning-top battle set including a launcher, two tops, and a plastic battle arena, popular for group play among older kids.',8500,null,80,10,'1 Set','set',1,'sinomart-toy-08',false,true,false);
select admin_seed_product('Inflatable Kiddie Ball Pit with 50 Balls','TOY-09','toyzone',array['toys'],'toys','Soft indoor play area for toddlers.','An inflatable ball pit bundled with 50 soft plastic balls, providing a safe, cushioned play space for indoor use.',19500,23000,40,6,'1 Set','set',1,'sinomart-toy-09',false,false,false);
select admin_seed_product('Magnetic Drawing Board','TOY-10','toyzone',array['toys','educational-toys'],'toys','Reusable magnetic doodle board for young artists.','A reusable magnetic drawing board with a stylus and sliding eraser, letting children draw and erase endlessly without paper.',5000,6000,145,12,'1 Piece','piece',1,'sinomart-toy-10',false,false,false);

-- ===== SCHOOL ESSENTIALS (kids-baby-toys, cross-listed with school-supplies) =====
select admin_seed_product('Kids Ergonomic School Backpack','SCE-01','chelino',array['school-essentials','bags-backpacks'],'school-essentials','Padded backpack designed for growing spines.','An ergonomically padded school backpack with adjustable straps and multiple compartments, sized for primary-school-aged children.',12500,15000,120,12,'1 Piece','piece',1,'sinomart-sce-01',true,true,true);
select admin_seed_product('36-Piece Colored Pencil Set','SCE-02','sinomart-essentials',array['school-essentials','stationery'],'school-essentials','Vivid, break-resistant pencils for schoolwork and art.','A set of 36 pre-sharpened colored pencils in a reusable tin case, formulated for smooth, break-resistant colouring.',3500,4200,220,20,'1 Set of 36','set',36,'sinomart-sce-02',false,false,true);
select admin_seed_product('Kids School Exercise Book Bundle (10 Pack)','SCE-03','sinomart-essentials',array['school-essentials','stationery'],'school-essentials','Ruled exercise books for daily classwork.','A bundle of ten 40-leaf ruled exercise books, sized to standard classroom requirements across Nigerian primary schools.',4500,null,300,25,'1 Bundle of 10','pack',10,'sinomart-sce-03',false,false,true);
select admin_seed_product('Reusable Water Bottle for School (Insulated)','SCE-04','chelino',array['school-essentials','drinkware'],'school-essentials','Leak-proof bottle sized for a school bag pocket.','An insulated, leak-proof bottle with a carry loop, sized to fit standard school bag side pockets while keeping drinks cool.',5500,6500,150,15,'1 Piece','piece',1,'sinomart-sce-04',false,false,false);
select admin_seed_product('Geometry Set with Compass and Ruler','SCE-05','sinomart-essentials',array['school-essentials','stationery'],'school-essentials','Complete geometry kit for maths class.','A complete geometry set including a compass, protractor, set squares, and ruler, packaged in a reusable hard case.',3200,null,190,18,'1 Set','set',1,'sinomart-sce-05',false,false,false);
select admin_seed_product('Kids Lunch Box & Bag Combo Set','SCE-06','chelino',array['school-essentials','lunch-boxes-flasks'],'school-essentials','Matching lunch box and insulated carry bag.','A coordinated lunch box and insulated carry bag set, keeping packed meals organized and at a safe temperature until lunchtime.',9500,11000,100,10,'1 Set','set',1,'sinomart-sce-06',false,false,false);
select admin_seed_product('School Uniform Name Labels (Pack of 50)','SCE-07','sinomart-essentials',array['school-essentials'],'school-essentials','Iron-on labels to identify school items.','Fifty iron-on fabric name labels, helping keep uniforms, bags, and gym kits correctly identified and returned if misplaced.',3000,null,130,12,'1 Pack of 50','pack',50,'sinomart-sce-07',false,false,false);
select admin_seed_product('Kids Study Desk Organizer','SCE-08','sinomart-essentials',array['school-essentials','office-supplies'],'school-essentials','Compartmentalised organizer for study supplies.','A compact desktop organizer with multiple compartments for pens, scissors, and small stationery, keeping study areas tidy.',4500,5200,110,10,'1 Piece','piece',1,'sinomart-sce-08',false,false,false);
select admin_seed_product('First-Day-of-School Stationery Bundle','SCE-09','sinomart-essentials',array['school-essentials','stationery'],'school-essentials','All-in-one starter pack for a new school year.','A bundled starter pack including exercise books, pencils, an eraser, ruler, and a pencil case — everything needed on day one.',7500,9000,140,12,'1 Bundle','set',1,'sinomart-sce-09',true,true,false);
select admin_seed_product('Reflective Safety School Vest','SCE-10','sinomart-essentials',array['school-essentials'],'school-essentials','High-visibility vest for the school run.','A lightweight reflective vest sized for children, improving visibility during early-morning or evening school commutes.',2500,null,160,15,'1 Piece','piece',1,'sinomart-sce-10',false,false,false);

-- ===== SKATES (sports-outdoor) =====
select admin_seed_product('Adjustable Kids Roller Skates','SKT-01','sinomart-essentials',array['skates'],'skates','Size-adjustable skates that grow with your child.','A pair of adjustable roller skates that expand across four sizes, extending usable life as a child''s foot grows.',13500,16000,90,10,'1 Pair','pair',1,'sinomart-skt-01',true,true,true);
select admin_seed_product('Inline Skates for Teens/Adults','SKT-02','sinomart-essentials',array['skates'],'skates','Speed-oriented inline skates with sturdy wheels.','A pair of inline skates with high-rebound urethane wheels and a reinforced ankle support shell, suited to teens and adults.',24500,28500,55,8,'1 Pair','pair',1,'sinomart-skt-02',false,false,false);
select admin_seed_product('Quad Roller Skates (Retro Style)','SKT-03','sinomart-essentials',array['skates'],'skates','Classic four-wheel skates for park and rink use.','A pair of retro-style quad roller skates with a padded high-top boot and smooth-rolling wheels for parks or rinks.',22000,null,60,8,'1 Pair','pair',1,'sinomart-skt-03',false,false,true);
select admin_seed_product('Protective Gear Set for Skating (Knee/Elbow/Wrist)','SKT-04','sinomart-essentials',array['skates','sports-equipment'],'skates','Full protective set for safer skating.','A complete protective set covering knees, elbows, and wrists, sized for children and recommended for all first-time skaters.',8500,10000,120,10,'1 Set','set',1,'sinomart-skt-04',false,false,false);
select admin_seed_product('Skate Helmet (Kids)','SKT-05','sinomart-essentials',array['skates','sports-equipment'],'skates','Impact-rated helmet sized for children.','A lightweight, ventilated helmet meeting impact-safety standards, adjustable to fit a range of child head sizes.',6500,7800,100,10,'1 Piece','piece',1,'sinomart-skt-05',false,false,false);
select admin_seed_product('Light-Up Wheel Roller Skates','SKT-06','sinomart-essentials',array['skates'],'skates','Skates with LED wheels that light up when rolling.','A pair of roller skates fitted with LED wheel lights that activate with motion, a popular choice for evening park sessions.',18500,null,65,8,'1 Pair','pair',1,'sinomart-skt-06',true,false,false);
select admin_seed_product('Skate Bag with Shoulder Strap','SKT-07','sinomart-essentials',array['skates','travel-bags'],'skates','Carry bag sized for skates and protective gear.','A durable carry bag with a padded shoulder strap and ventilated compartment, sized to transport skates and safety gear together.',6000,null,85,8,'1 Piece','piece',1,'sinomart-skt-07',false,false,false);
select admin_seed_product('Replacement Skate Wheels (Set of 8)','SKT-08','sinomart-essentials',array['skates'],'skates','Spare wheels to extend the life of your skates.','A set of eight replacement urethane skate wheels compatible with most standard quad and inline skate frames.',7500,9000,70,8,'1 Set of 8','set',8,'sinomart-skt-08',false,false,false);
select admin_seed_product('Beginner Skateboard-Style Balance Trainer','SKT-09','sinomart-essentials',array['skates','skateboards'],'skates','Low platform trainer to build balance before skating.','A low, wide balance-training board that helps first-time skaters build core balance and confidence before moving to full skates.',9500,11000,50,6,'1 Piece','piece',1,'sinomart-skt-09',false,true,false);
select admin_seed_product('Skate Tool & Maintenance Kit','SKT-10','sinomart-essentials',array['skates'],'skates','Compact toolkit for tightening and maintaining skates.','A compact multi-tool kit for tightening trucks, swapping wheels, and general skate maintenance, sized to fit in a skate bag.',3500,null,95,8,'1 Piece','piece',1,'sinomart-skt-10',false,false,false);

-- ===== SCHOOL SUPPLIES (office-school) =====
select admin_seed_product('A4 Ring Binder Files (Pack of 5)','SSU-01','sinomart-essentials',array['school-supplies','office-supplies'],'school-supplies','Sturdy ring binders for filing and study notes.','Five A4 ring binder files with reinforced spines, suited to organizing school notes, assignments, or office paperwork.',5500,6500,180,15,'1 Pack of 5','pack',5,'sinomart-ssu-01',false,false,true);
select admin_seed_product('Scientific Calculator','SSU-02','sinomart-essentials',array['school-supplies','stationery'],'school-supplies','Exam-approved scientific calculator.','A scientific calculator supporting standard trigonometric, statistical, and algebraic functions, suitable for secondary and tertiary exams.',8500,10000,140,12,'1 Piece','piece',1,'sinomart-ssu-02',true,false,true);
select admin_seed_product('A4 Printer Paper Ream (500 Sheets)','SSU-03','sinomart-essentials',array['school-supplies','office-supplies'],'school-supplies','Everyday paper for printing and copying.','A 500-sheet ream of A4 printer paper suited to everyday school and office printing, copying, and general document use.',4200,null,260,20,'1 Ream','pack',500,'sinomart-ssu-03',false,false,false);
select admin_seed_product('Highlighter Marker Set (6 Colors)','SSU-04','sinomart-essentials',array['school-supplies','stationery'],'school-supplies','Bright highlighters for notes and revision.','A set of six brightly coloured highlighter markers with a chisel tip, ideal for revision notes and colour-coded studying.',3000,3600,200,18,'1 Set of 6','set',6,'sinomart-ssu-04',false,false,false);
select admin_seed_product('Wireless Mouse for Study/Office Use','SSU-05','sinomart-essentials',array['school-supplies','office-supplies'],'school-supplies','Reliable wireless mouse for laptops and PCs.','A compact wireless optical mouse with a USB receiver, suited to students and office workers using laptops for coursework or tasks.',5500,6800,150,12,'1 Piece','piece',1,'sinomart-ssu-05',false,false,false);
select admin_seed_product('Correction Tape (Pack of 3)','SSU-06','sinomart-essentials',array['school-supplies','stationery'],'school-supplies','Clean, dry correction tape for neat edits.','Three correction tape rollers offering a clean, dry alternative to correction fluid for tidy handwritten corrections.',2500,null,220,18,'1 Pack of 3','pack',3,'sinomart-ssu-06',false,false,false);
select admin_seed_product('Laptop Backpack with USB Charging Port','SSU-07','sinomart-essentials',array['school-supplies','bags-backpacks'],'school-supplies','Padded backpack for laptops and school files.','A padded laptop backpack with a dedicated sleeve and an external USB charging port, suited to students carrying a laptop daily.',14500,17000,90,10,'1 Piece','piece',1,'sinomart-ssu-07',true,false,false);
select admin_seed_product('Sticky Notes Multi-Pack (12 Pads)','SSU-08','sinomart-essentials',array['school-supplies','stationery'],'school-supplies','Assorted sticky notes for reminders and notes.','A twelve-pad multi-pack of sticky notes in assorted sizes and colours, useful for revision, reminders, and organizing tasks.',3500,4200,175,15,'1 Pack of 12','pack',12,'sinomart-ssu-08',false,false,false);
select admin_seed_product('Mechanical Pencil Set with Refills','SSU-09','sinomart-essentials',array['school-supplies','stationery'],'school-supplies','Consistent, no-sharpen pencils for daily writing.','A set of three mechanical pencils with extra lead refills, removing the need for repeated sharpening during exams or classwork.',3200,null,190,16,'1 Set','set',1,'sinomart-ssu-09',false,false,false);
select admin_seed_product('Whiteboard with Marker (Portable, A3)','SSU-10','sinomart-essentials',array['school-supplies','educational-materials'],'school-supplies','Reusable whiteboard for practice and revision.','A portable A3 whiteboard bundled with a dry-erase marker, useful for practising maths problems or quick visual explanations.',5500,6500,110,10,'1 Piece','piece',1,'sinomart-ssu-10',false,false,false);
