-- =====================================================================================
-- 024_seed_products_part5.sql — Pet Supplies: Pet Toys
--                                Travel & Luggage: Suitcases
--                                Groceries & Everyday Essentials: Household Essentials
--                                Tools & Hardware: Hand Tools
-- =====================================================================================

-- ===== PET TOYS (pet-supplies) =====
select admin_seed_product('Squeaky Plush Dog Toy (Bone Shape)','PTY-01','sinomart-essentials',array['pet-toys'],'pet-toys','Durable plush toy with an internal squeaker.','A plush bone-shaped dog toy with a reinforced internal squeaker, stitched with double seams to withstand energetic chewing.',3500,4200,150,15,'1 Piece','piece',1,'sinomart-pty-01',true,false,true);
select admin_seed_product('Interactive Feather Wand Cat Toy','PTY-02','sinomart-essentials',array['pet-toys'],'pet-toys','Wand toy to encourage active play with cats.','A feather-and-bell wand toy on a flexible rod, designed to trigger a cat''s natural chase-and-pounce instincts during play sessions.',2800,null,170,15,'1 Piece','piece',1,'sinomart-pty-02',false,false,false);
select admin_seed_product('Durable Rubber Chew Toy for Dogs','PTY-03','sinomart-essentials',array['pet-toys'],'pet-toys','Tough rubber toy for heavy chewers.','A dense rubber chew toy with an irregular bounce pattern, built to withstand sustained chewing from medium to large dogs.',4500,5400,120,12,'1 Piece','piece',1,'sinomart-pty-03',false,false,true);
select admin_seed_product('Automatic Laser Pointer Cat Toy','PTY-04','sinomart-essentials',array['pet-toys'],'pet-toys','Hands-free laser toy for solo cat play.','A battery-powered automatic laser toy that moves in randomized patterns, keeping cats engaged even when owners are away.',6500,7800,90,10,'1 Piece','piece',1,'sinomart-pty-04',false,true,false);
select admin_seed_product('Rope Tug Toy for Dogs','PTY-05','sinomart-essentials',array['pet-toys'],'pet-toys','Cotton rope toy for tug-of-war and chewing.','A tightly woven cotton rope toy suited to tug-of-war play, also helping support dental health through natural chewing action.',2500,null,180,15,'1 Piece','piece',1,'sinomart-pty-05',false,false,false);
select admin_seed_product('Treat-Dispensing Puzzle Ball','PTY-06','sinomart-essentials',array['pet-toys'],'pet-toys','Mental stimulation toy that rewards with treats.','A treat-dispensing puzzle ball that releases kibble as it rolls, encouraging mental stimulation and slower, healthier eating.',4800,5800,95,10,'1 Piece','piece',1,'sinomart-pty-06',false,false,false);
select admin_seed_product('Crinkle Tunnel Cat Play Toy','PTY-07','sinomart-essentials',array['pet-toys'],'pet-toys','Collapsible tunnel with crinkle sound.','A collapsible fabric play tunnel with a built-in crinkle layer, giving cats a hiding and pouncing spot that folds flat for storage.',6000,null,70,8,'1 Piece','piece',1,'sinomart-pty-07',false,false,false);
select admin_seed_product('Small Animal Chew Sticks (Pack of 10)','PTY-08','sinomart-essentials',array['pet-toys','pet-food-treats'],'pet-toys','Natural chew sticks for rabbits and small pets.','A pack of ten natural fibre chew sticks, helping small pets like rabbits and guinea pigs wear down their teeth safely.',3200,3800,110,10,'1 Pack of 10','pack',10,'sinomart-pty-08',false,false,false);
select admin_seed_product('Flying Disc Dog Toy','PTY-09','sinomart-essentials',array['pet-toys'],'pet-toys','Soft flying disc for outdoor fetch sessions.','A flexible, bite-resistant flying disc designed for outdoor fetch games, gentle enough on a dog''s mouth during catches.',3800,null,100,10,'1 Piece','piece',1,'sinomart-pty-09',false,false,false);
select admin_seed_product('Cat Scratching Post Toy Combo','PTY-10','sinomart-essentials',array['pet-toys'],'pet-toys','Scratching post combined with a hanging toy.','A compact scratching post wrapped in sisal rope, topped with a hanging ball toy to combine claw care with active play.',9500,11000,60,8,'1 Piece','piece',1,'sinomart-pty-10',false,false,false);

-- ===== SUITCASES (travel-luggage) =====
select admin_seed_product('20" Hardshell Cabin Suitcase','SUI-01','sinomart-essentials',array['suitcases'],'suitcases','Lightweight cabin-sized suitcase with spinner wheels.','A 20-inch hardshell suitcase built for cabin-baggage allowances, with 360-degree spinner wheels and a TSA-approved combination lock.',24500,29000,60,8,'1 Piece','piece',1,'sinomart-sui-01',true,true,true);
select admin_seed_product('28" Hardshell Check-In Suitcase','SUI-02','sinomart-essentials',array['suitcases'],'suitcases','Large-capacity suitcase for extended travel.','A 28-inch hardshell check-in suitcase with an expandable zip and reinforced corners, sized for extended trips or family packing.',34500,40000,40,6,'1 Piece','piece',1,'sinomart-sui-02',false,false,true);
select admin_seed_product('24" Softshell Expandable Suitcase','SUI-03','sinomart-essentials',array['suitcases'],'suitcases','Flexible softshell case with extra packing room.','A 24-inch softshell suitcase with an expandable main compartment and multiple exterior pockets for last-minute items.',27500,null,45,6,'1 Piece','piece',1,'sinomart-sui-03',false,false,false);
select admin_seed_product('3-Piece Luggage Set (Small, Medium, Large)','SUI-04','sinomart-essentials',array['suitcases'],'suitcases','Matching suitcase trio for any trip length.','A coordinated three-piece hardshell luggage set covering cabin, medium, and large check-in sizes for trips of any length.',68000,79000,25,5,'1 Set of 3','set',3,'sinomart-sui-04',true,false,false);
select admin_seed_product('Kids Ride-On Suitcase','SUI-05','chelino',array['suitcases','kids-fashion'],'suitcases','Fun rideable suitcase for young travellers.','A child-sized hardshell suitcase with a built-in seat and pull strap, letting younger travellers ride along through the airport.',18500,21500,35,6,'1 Piece','piece',1,'sinomart-sui-05',false,true,false);
select admin_seed_product('Luggage Scale (Digital, Handheld)','SUI-06','sinomart-essentials',array['suitcases','travel-accessories'],'suitcases','Portable scale to avoid excess baggage fees.','A handheld digital luggage scale with a strap hook, letting travellers weigh bags at home before heading to the airport.',3500,null,110,10,'1 Piece','piece',1,'sinomart-sui-06',false,false,false);
select admin_seed_product('Suitcase Protective Cover (Large)','SUI-07','sinomart-essentials',array['suitcases'],'suitcases','Stretch cover to protect luggage in transit.','A stretchable protective cover sized for large suitcases, guarding against scuffs and scratches during flights.',4500,5400,90,8,'1 Piece','piece',1,'sinomart-sui-07',false,false,false);
select admin_seed_product('TSA-Approved Luggage Locks (Set of 2)','SUI-08','sinomart-essentials',array['suitcases','travel-accessories'],'suitcases','Combination locks accepted for air travel.','Two TSA-approved combination padlocks, letting security agents inspect luggage without needing to cut the lock.',3200,null,140,12,'1 Set of 2','set',2,'sinomart-sui-08',false,false,false);
select admin_seed_product('22" Lightweight Spinner Suitcase','SUI-09','sinomart-essentials',array['suitcases'],'suitcases','Ultra-light case for frequent flyers.','A 22-inch spinner suitcase built from a lightweight polycarbonate shell, aimed at frequent flyers watching baggage weight limits.',26500,31000,50,6,'1 Piece','piece',1,'sinomart-sui-09',false,false,false);
select admin_seed_product('Packing Cube Organizer Set (6 Pieces)','SUI-10','sinomart-essentials',array['suitcases','travel-organizers'],'suitcases','Compression cubes to organize suitcase contents.','A set of six packing cubes in varied sizes, keeping folded clothing compressed, organized, and easy to locate inside a suitcase.',7500,8800,100,10,'1 Set of 6','set',6,'sinomart-sui-10',false,false,false);

-- ===== HOUSEHOLD ESSENTIALS (groceries-essentials) =====
select admin_seed_product('All-Purpose Cleaning Spray 750ml','HHE-01','sinomart-essentials',array['household-essentials'],'household-essentials','Multi-surface cleaner for everyday spills.','A multi-surface cleaning spray effective on kitchen counters, bathroom tiles, and general household surfaces.',2200,2600,260,20,'1 Piece','piece',1,'sinomart-hhe-01',false,false,true);
select admin_seed_product('Laundry Detergent Powder 3kg','HHE-02','sinomart-essentials',array['household-essentials','cleaning-laundry'],'household-essentials','Stain-fighting powder for regular laundry loads.','A 3kg laundry detergent powder formulated to lift everyday stains while remaining gentle on fabric colour and texture.',5500,6200,200,18,'1 Piece','piece',1,'sinomart-hhe-02',true,false,true);
select admin_seed_product('Dishwashing Liquid Soap 1L','HHE-03','sinomart-essentials',array['household-essentials'],'household-essentials','Grease-cutting liquid soap for daily dishwashing.','A concentrated dishwashing liquid that cuts through grease efficiently, formulated to be gentle on hands with regular use.',2500,null,240,20,'1 Piece','piece',1,'sinomart-hhe-03',false,false,false);
select admin_seed_product('Toilet Tissue Rolls (Pack of 12)','HHE-04','sinomart-essentials',array['household-essentials'],'household-essentials','Soft, absorbent tissue for everyday bathroom use.','A twelve-roll pack of two-ply toilet tissue, balancing softness and absorbency for everyday household use.',4200,4800,300,25,'1 Pack of 12','pack',12,'sinomart-hhe-04',false,false,true);
select admin_seed_product('Air Freshener Spray (Lavender) 300ml','HHE-05','sinomart-essentials',array['household-essentials'],'household-essentials','Long-lasting fragrance for any room.','A lavender-scented air freshener spray offering a long-lasting, non-overpowering fragrance for living rooms and bathrooms.',2000,null,220,18,'1 Piece','piece',1,'sinomart-hhe-05',false,false,false);
select admin_seed_product('Insect Repellent Spray 400ml','HHE-06','sinomart-essentials',array['household-essentials'],'household-essentials','Fast-acting spray against flies and mosquitoes.','A fast-acting insect spray effective against flying and crawling insects, suited to indoor household use.',2800,3300,190,16,'1 Piece','piece',1,'sinomart-hhe-06',false,false,false);
select admin_seed_product('Microfiber Cleaning Cloths (Pack of 6)','HHE-07','sinomart-essentials',array['household-essentials','cleaning-laundry'],'household-essentials','Lint-free cloths for dusting and polishing.','Six lint-free microfiber cloths suited to dusting, polishing, and general surface cleaning without leaving streaks.',3000,null,180,15,'1 Pack of 6','pack',6,'sinomart-hhe-07',false,false,false);
select admin_seed_product('Bathroom & Tile Cleaner 500ml','HHE-08','sinomart-essentials',array['household-essentials','bathroom'],'household-essentials','Tough cleaner for soap scum and grime.','A bathroom-specific cleaner formulated to cut through soap scum, water stains, and grime on tiles and fittings.',2600,3100,170,15,'1 Piece','piece',1,'sinomart-hhe-08',false,false,false);
select admin_seed_product('Heavy-Duty Trash Bags (Roll of 30)','HHE-09','sinomart-essentials',array['household-essentials'],'household-essentials','Tear-resistant bags for daily household waste.','A roll of thirty tear-resistant trash bags, sized for standard household bins and daily waste disposal.',2500,null,210,18,'1 Roll of 30','pack',30,'sinomart-hhe-09',false,false,false);
select admin_seed_product('Fabric Softener 1L','HHE-10','sinomart-essentials',array['household-essentials','cleaning-laundry'],'household-essentials','Softens fabric and reduces static after washing.','A concentrated fabric softener that leaves laundry feeling softer and smelling fresh while reducing static cling.',3200,3800,175,15,'1 Piece','piece',1,'sinomart-hhe-10',false,false,false);

-- ===== HAND TOOLS (tools-hardware) =====
select admin_seed_product('45-Piece Household Tool Kit','HTL-01','sinomart-essentials',array['hand-tools'],'hand-tools','All-in-one toolkit for common home repairs.','A 45-piece household toolkit including a hammer, screwdrivers, pliers, and a tape measure, packaged in a durable carry case.',15500,18500,80,10,'1 Set','set',1,'sinomart-htl-01',true,true,true);
select admin_seed_product('Claw Hammer 16oz','HTL-02','sinomart-essentials',array['hand-tools'],'hand-tools','Balanced hammer for driving and pulling nails.','A 16oz claw hammer with a fibreglass-reinforced handle and shock-absorbing grip, suited to general household use.',4500,null,150,15,'1 Piece','piece',1,'sinomart-htl-02',false,false,false);
select admin_seed_product('Adjustable Wrench Set (3 Pieces)','HTL-03','sinomart-essentials',array['hand-tools'],'hand-tools','Graduated wrenches for varied bolt sizes.','Three adjustable wrenches in graduated sizes, covering a wide range of nut and bolt dimensions for household and light mechanical work.',6500,7800,110,10,'1 Set of 3','set',3,'sinomart-htl-03',false,false,false);
select admin_seed_product('Cordless Electric Screwdriver Set','HTL-04','sinomart-essentials',array['hand-tools','workshop-equipment'],'hand-tools','Rechargeable screwdriver with multiple bits.','A rechargeable cordless screwdriver with an assortment of interchangeable bits, speeding up assembly and repair tasks.',12500,15000,65,8,'1 Set','set',1,'sinomart-htl-04',true,false,true);
select admin_seed_product('Measuring Tape 5m','HTL-05','sinomart-essentials',array['hand-tools'],'hand-tools','Retractable tape measure with a locking blade.','A 5-metre retractable measuring tape with a locking mechanism and easy-to-read markings for household measuring tasks.',2800,null,190,15,'1 Piece','piece',1,'sinomart-htl-05',false,false,false);
select admin_seed_product('Multi-Bit Screwdriver Set (12 Pieces)','HTL-06','sinomart-essentials',array['hand-tools'],'hand-tools','Interchangeable bits for varied screw types.','A twelve-piece screwdriver set with interchangeable magnetic bits, covering Phillips, flathead, and specialty screw types.',4200,5000,140,12,'1 Set of 12','set',12,'sinomart-htl-06',false,false,false);
select admin_seed_product('Utility Knife with Retractable Blade','HTL-07','sinomart-essentials',array['hand-tools'],'hand-tools','Sturdy cutting tool for boxes and packaging.','A retractable utility knife with a locking blade mechanism and ergonomic grip, useful for opening boxes and general cutting tasks.',2200,null,220,18,'1 Piece','piece',1,'sinomart-htl-07',false,false,false);
select admin_seed_product('Plier Set (3 Types)','HTL-08','sinomart-essentials',array['hand-tools'],'hand-tools','Combination, needle-nose, and cutting pliers.','Three plier types — combination, needle-nose, and diagonal cutting — covering most common household gripping and cutting tasks.',5800,6900,100,10,'1 Set of 3','set',3,'sinomart-htl-08',false,false,false);
select admin_seed_product('Heavy-Duty Staple Gun','HTL-09','sinomart-essentials',array['hand-tools','workshop-equipment'],'hand-tools','Manual staple gun for upholstery and repairs.','A manual heavy-duty staple gun suited to upholstery, light carpentry, and general fastening tasks around the home.',6500,null,75,8,'1 Piece','piece',1,'sinomart-htl-09',false,false,false);
select admin_seed_product('Tool Storage Box with Tray','HTL-10','sinomart-essentials',array['hand-tools','storage-organization'],'hand-tools','Portable box to keep tools organized.','A portable plastic toolbox with a lift-out tray, keeping small tools and hardware sorted and easy to transport.',5500,6500,95,10,'1 Piece','piece',1,'sinomart-htl-10',false,false,false);

-- ===== A FEW OUT-OF-STOCK / EDGE-CASE DEMO PRODUCTS (illustrate stock-state variety) =====
select admin_seed_product('55" 4K UHD Smart TV — Limited Stock Unit','TVE-11','samsung',array['televisions'],'televisions','Clearance unit, very limited quantity remaining.','A final clearance batch of our 55-inch 4K smart TV line, while stocks last.',329000,360000,2,5,'1 Piece','piece',1,'sinomart-tve-11',false,false,false);
select admin_seed_product('Portable Rechargeable Standing Fan — Sold Out','FAN-11','binatone',array['fans'],'fans','Currently out of stock; restock expected soon.','Our most popular rechargeable standing fan, currently out of stock while we await the next shipment.',28500,null,0,10,'1 Piece','piece',1,'sinomart-fan-11',false,false,false);
