-- =====================================================================================
-- 027_seed_products_part7.sql — Home & Living: Storage & Organization
--                                Kitchen & Dining: Kitchen Utensils
--                                Electronics & Appliances: Small Kitchen Appliances
-- =====================================================================================

-- ===== STORAGE & ORGANIZATION (home-living) =====
select admin_seed_product('Clear Stackable Storage Bins (Set of 3)','STO-01','sinomart-essentials',array['storage-organization'],'storage-organization','Transparent bins for easy-to-see storage.','Three clear plastic storage bins with snap-fit lids, letting you see contents at a glance while stacking neatly in closets or pantries.',9500,11000,150,15,'1 Set of 3','set',3,'sinomart-sto-01',true,false,true);
select admin_seed_product('Under-Bed Storage Bags (Set of 2)','STO-02','sinomart-essentials',array['storage-organization','bedroom'],'storage-organization','Flat storage bags for out-of-season items.','Two zippered under-bed storage bags with reinforced handles, ideal for storing out-of-season clothing or spare bedding.',6500,null,120,12,'1 Set of 2','set',2,'sinomart-sto-02',false,false,false);
select admin_seed_product('Wall-Mounted Hook Organizer Rail','STO-03','sinomart-essentials',array['storage-organization'],'storage-organization','Multi-hook rail for coats, bags, and keys.','A wall-mounted rail with six sturdy hooks, useful near entryways for coats, bags, umbrellas, and keys.',5500,6500,140,12,'1 Piece','piece',1,'sinomart-sto-03',false,false,false);
select admin_seed_product('Vacuum Storage Bags (Pack of 6)','STO-04','sinomart-essentials',array['storage-organization'],'storage-organization','Space-saving bags that compress with a vacuum.','Six vacuum-seal storage bags that compress bulky items like duvets and winter clothing to a fraction of their original size.',7000,8200,110,10,'1 Pack of 6','pack',6,'sinomart-sto-04',false,true,false);
select admin_seed_product('Drawer Divider Organizer Set','STO-05','sinomart-essentials',array['storage-organization'],'storage-organization','Adjustable dividers to tidy drawers.','An adjustable set of drawer dividers that expand to fit varying drawer widths, keeping folded clothing or utensils separated.',4500,null,160,14,'1 Set','set',1,'sinomart-sto-05',false,false,false);
select admin_seed_product('Over-Door Shoe & Accessory Organizer','STO-06','sinomart-essentials',array['storage-organization','bathroom'],'storage-organization','Hanging pockets for shoes or toiletries.','A 24-pocket hanging organizer that mounts over any standard door, useful for shoes, toiletries, or small accessories.',6800,7800,95,10,'1 Piece','piece',1,'sinomart-sto-06',false,false,false);
select admin_seed_product('Stackable Plastic Storage Drawers (3-Tier)','STO-07','sinomart-essentials',array['storage-organization'],'storage-organization','Rolling drawer unit for clothing or supplies.','A three-tier stackable plastic drawer unit on castors, easy to roll between rooms while keeping contents organized.',14500,17000,70,8,'1 Piece','piece',1,'sinomart-sto-07',false,false,false);
select admin_seed_product('Cable & Cord Organizer Box','STO-08','sinomart-essentials',array['storage-organization','gadgets-accessories'],'storage-organization','Hides and organizes messy charging cables.','A ventilated cable-management box that conceals power strips and cords, tidying up entertainment units and desks.',3800,null,150,12,'1 Piece','piece',1,'sinomart-sto-08',false,false,false);
select admin_seed_product('Jewelry & Accessory Organizer Tray','STO-09','sinomart-essentials',array['storage-organization','jewellery'],'storage-organization','Compartmentalised tray for rings and earrings.','A velvet-lined organizer tray with multiple compartments, keeping rings, earrings, and small accessories from tangling.',4200,5000,130,12,'1 Piece','piece',1,'sinomart-sto-09',false,false,false);
select admin_seed_product('Pantry Storage Container Set (Airtight, 6 Piece)','STO-10','sinomart-essentials',array['storage-organization','food-storage'],'storage-organization','Airtight containers to keep dry goods fresh.','Six airtight pantry containers with click-seal lids, keeping rice, flour, and grains fresh and free from pests.',10500,12500,100,10,'1 Set of 6','set',6,'sinomart-sto-10',true,false,false);

-- ===== KITCHEN UTENSILS (kitchen-dining) =====
select admin_seed_product('Silicone Kitchen Utensil Set (10 Piece)','UTN-01','sinomart-essentials',array['kitchen-utensils'],'kitchen-utensils','Heat-resistant utensils safe on non-stick pans.','A 10-piece silicone utensil set including spatulas, ladle, and tongs, safe on non-stick cookware and heat-resistant up to high temperatures.',9500,11500,180,18,'1 Set of 10','set',10,'sinomart-utn-01',true,false,true);
select admin_seed_product('Stainless Steel Knife Set with Block','UTN-02','sinomart-essentials',array['kitchen-utensils'],'kitchen-utensils','Six essential knives in a wooden block.','A six-piece stainless-steel knife set covering chef, bread, and paring knives, stored in a wooden countertop block.',15500,18000,90,10,'1 Set','set',1,'sinomart-utn-02',false,false,true);
select admin_seed_product('Wooden Chopping Board (Large)','UTN-03','sinomart-essentials',array['kitchen-utensils'],'kitchen-utensils','Durable board for everyday food prep.','A large wooden chopping board with a juice groove, gentle on knife edges and durable enough for daily meal prep.',5500,null,150,14,'1 Piece','piece',1,'sinomart-utn-03',false,false,false);
select admin_seed_product('Manual Hand Whisk','UTN-04','sinomart-essentials',array['kitchen-utensils','baking-kitchen-tools'],'kitchen-utensils','Sturdy whisk for eggs, batter, and sauces.','A stainless-steel balloon whisk with a comfortable grip, suited to whisking eggs, batter, or smoothing out sauces.',2200,null,220,18,'1 Piece','piece',1,'sinomart-utn-04',false,false,false);
select admin_seed_product('Vegetable Peeler & Grater Set','UTN-05','sinomart-essentials',array['kitchen-utensils'],'kitchen-utensils','Sharp, comfortable tools for daily prep.','A peeler and box grater set with ergonomic handles, built to make daily vegetable and cheese prep quicker.',3200,3800,190,16,'1 Set','set',1,'sinomart-utn-05',false,false,false);
select admin_seed_product('Stainless Steel Colander/Strainer','UTN-06','sinomart-essentials',array['kitchen-utensils'],'kitchen-utensils','Wide colander for draining pasta or rice.','A wide stainless-steel colander with sturdy side handles and a stable base, sized for draining pasta, rice, or washed produce.',4500,null,160,14,'1 Piece','piece',1,'sinomart-utn-06',false,false,false);
select admin_seed_product('Kitchen Scissors (Heavy-Duty)','UTN-07','sinomart-essentials',array['kitchen-utensils'],'kitchen-utensils','Multi-purpose scissors for meat and packaging.','Heavy-duty kitchen scissors with a built-in bottle opener and nutcracker notch, useful well beyond ordinary cutting tasks.',2800,3400,170,15,'1 Piece','piece',1,'sinomart-utn-07',false,false,false);
select admin_seed_product('Garlic Press with Cleaning Brush','UTN-08','sinomart-essentials',array['kitchen-utensils'],'kitchen-utensils','Crushes garlic quickly without peeling.','A sturdy garlic press that crushes cloves without needing to peel first, bundled with a small cleaning brush.',2500,null,200,15,'1 Piece','piece',1,'sinomart-utn-08',false,false,false);
select admin_seed_product('Measuring Cups & Spoons Set','UTN-09','sinomart-essentials',array['kitchen-utensils','baking-kitchen-tools'],'kitchen-utensils','Precise measuring set for cooking and baking.','A stainless-steel measuring cup and spoon set covering standard cooking and baking measurements, nested for compact storage.',3500,4200,180,15,'1 Set','set',1,'sinomart-utn-09',false,false,false);
select admin_seed_product('Non-Stick Turner & Ladle Set (5 Piece)','UTN-10','sinomart-essentials',array['kitchen-utensils'],'kitchen-utensils','Everyday cooking tools in a hanging set.','A five-piece cooking tool set with a hanging rack, covering turners, ladles, and spoons for everyday stovetop cooking.',6500,7500,140,12,'1 Set of 5','set',5,'sinomart-utn-10',false,false,false);

-- ===== SMALL KITCHEN APPLIANCES (electronics-appliances) =====
select admin_seed_product('Electric Blender 1.5L','SKA-01','binatone',array['small-kitchen-appliances'],'small-kitchen-appliances','Powerful blender for smoothies and sauces.','A 1.5-litre electric blender with multiple speed settings and a pulse function, suited to smoothies, sauces, and soups.',16500,19500,90,10,'1 Piece','piece',1,'sinomart-ska-01',true,false,true);
select admin_seed_product('4-Slice Toaster','SKA-02','binatone',array['small-kitchen-appliances'],'small-kitchen-appliances','Wide-slot toaster for bread and bagels.','A four-slice toaster with wide slots and adjustable browning control, suited to bread, bagels, and thicker slices.',12500,null,75,10,'1 Piece','piece',1,'sinomart-ska-02',false,false,false);
select admin_seed_product('Electric Kettle 1.7L','SKA-03','binatone',array['small-kitchen-appliances'],'small-kitchen-appliances','Fast-boil kettle with auto shut-off.','A 1.7-litre electric kettle with rapid boil and automatic shut-off once water reaches boiling point.',9500,11000,130,12,'1 Piece','piece',1,'sinomart-ska-03',true,false,true);
select admin_seed_product('Air Fryer 4.5L','SKA-04','binatone',array['small-kitchen-appliances'],'small-kitchen-appliances','Oil-free frying with a digital control panel.','A 4.5-litre digital air fryer offering oil-free crisping for fries, chicken, and vegetables, with programmable presets.',34500,40000,55,8,'1 Piece','piece',1,'sinomart-ska-04',true,true,true);
select admin_seed_product('Hand Mixer with Attachments','SKA-05','binatone',array['small-kitchen-appliances','baking-kitchen-tools'],'small-kitchen-appliances','Electric mixer for batters and cream.','A handheld electric mixer with multiple speed settings and interchangeable beaters, suited to cakes, batters, and whipped cream.',11500,13500,80,8,'1 Piece','piece',1,'sinomart-ska-05',false,false,false);
select admin_seed_product('Sandwich & Panini Press','SKA-06','binatone',array['small-kitchen-appliances'],'small-kitchen-appliances','Non-stick press for toasted sandwiches.','A compact non-stick sandwich press with indicator lights, turning out evenly toasted sandwiches in minutes.',10500,null,65,8,'1 Piece','piece',1,'sinomart-ska-06',false,false,false);
select admin_seed_product('Electric Coffee Maker 1.2L','SKA-07','binatone',array['small-kitchen-appliances','drinkware'],'small-kitchen-appliances','Drip coffee maker with a glass carafe.','A drip-style coffee maker with a 1.2-litre glass carafe and keep-warm plate, brewing enough coffee for several cups.',15500,18000,60,8,'1 Piece','piece',1,'sinomart-ska-07',false,false,false);
select admin_seed_product('Slow Cooker 4L','SKA-08','binatone',array['small-kitchen-appliances'],'small-kitchen-appliances','Low, steady heat for tender stews.','A 4-litre slow cooker with high/low/warm settings, ideal for tenderizing beans, meat, and slow-cooked stews.',19500,23000,45,6,'1 Piece','piece',1,'sinomart-ska-08',false,false,false);
select admin_seed_product('Hand Blender with Chopper Attachment','SKA-09','binatone',array['small-kitchen-appliances'],'small-kitchen-appliances','Compact immersion blender for soups and purées.','An immersion hand blender with a detachable chopper attachment, useful for blending soups directly in the pot.',12500,null,70,8,'1 Piece','piece',1,'sinomart-ska-09',false,false,false);
select admin_seed_product('Electric Deep Fryer 2.5L','SKA-10','binatone',array['small-kitchen-appliances'],'small-kitchen-appliances','Temperature-controlled fryer with basket.','A 2.5-litre electric deep fryer with adjustable temperature control and a removable frying basket for easy draining.',22500,26000,40,6,'1 Piece','piece',1,'sinomart-ska-10',false,false,false);
