-- =====================================================================================
-- 028_seed_products_part8.sql — Fashion & Accessories: Bags
--                                Beauty & Personal Care: Makeup
--                                Kids, Baby & Toys: Baby Care
-- =====================================================================================

-- ===== BAGS (fashion-accessories) =====
select admin_seed_product('Women''s Structured Tote Bag','BAG-01','sinomart-essentials',array['bags'],'bags','Spacious tote for work or daily errands.','A structured tote bag in a durable PU leather finish, with a wide opening and interior pockets for daily essentials.',12500,15000,110,10,'1 Piece','piece',1,'sinomart-bag-01',true,true,true);
select admin_seed_product('Men''s Crossbody Sling Bag','BAG-02','sinomart-essentials',array['bags'],'bags','Compact bag for phone, wallet, and keys.','A slim crossbody sling bag with adjustable strap and multiple compartments, sized for daily essentials without bulk.',7500,9000,140,12,'1 Piece','piece',1,'sinomart-bag-02',false,false,true);
select admin_seed_product('Quilted Chain-Strap Shoulder Bag','BAG-03','sinomart-essentials',array['bags'],'bags','Classic quilted design with a metal chain strap.','A quilted shoulder bag with a metal chain strap detail, a versatile option for both casual and dressier outfits.',9500,null,95,10,'1 Piece','piece',1,'sinomart-bag-03',false,false,false);
select admin_seed_product('Canvas Tote Bag with Zip Closure','BAG-04','sinomart-essentials',array['bags'],'bags','Durable everyday canvas tote.','A sturdy canvas tote with a zip closure and reinforced base, suited to grocery runs, gym kit, or everyday carrying.',5500,6500,180,15,'1 Piece','piece',1,'sinomart-bag-04',false,false,false);
select admin_seed_product('Women''s Clutch Purse (Evening)','BAG-05','sinomart-essentials',array['bags'],'bags','Compact clutch for evenings and events.','A compact evening clutch with a detachable chain strap, sized for essentials at parties, weddings, or dinners.',6500,7800,85,8,'1 Piece','piece',1,'sinomart-bag-05',false,false,false);
select admin_seed_product('Men''s Leather-Effect Briefcase','BAG-06','sinomart-essentials',array['bags','office-furniture'],'bags','Structured briefcase for laptops and files.','A structured briefcase in a leather-effect finish with a padded laptop compartment, suited to office and business use.',18500,21500,55,6,'1 Piece','piece',1,'sinomart-bag-06',false,false,false);
select admin_seed_product('Waist Bag / Fanny Pack','BAG-07','sinomart-essentials',array['bags'],'bags','Hands-free bag for outings and travel.','An adjustable waist bag with multiple pockets, popular for hands-free carrying during outings, errands, or travel.',4500,null,150,12,'1 Piece','piece',1,'sinomart-bag-07',false,true,false);
select admin_seed_product('Woven Straw Beach Bag','BAG-08','sinomart-essentials',array['bags'],'bags','Lightweight bag for beach or poolside days.','A handwoven straw-style beach bag with a roomy interior and sturdy handles, suited to beach days and summer outings.',6000,7200,90,8,'1 Piece','piece',1,'sinomart-bag-08',false,false,false);
select admin_seed_product('Convertible Backpack-Handbag','BAG-09','sinomart-essentials',array['bags'],'bags','Switches between backpack and handbag styles.','A convertible bag with detachable straps, switching easily between a backpack and a top-handle handbag depending on the day.',10500,12500,75,8,'1 Piece','piece',1,'sinomart-bag-09',false,false,false);
select admin_seed_product('Men''s Canvas Messenger Bag','BAG-10','sinomart-essentials',array['bags'],'bags','Rugged messenger bag for daily carry.','A canvas messenger bag with an adjustable strap and a padded laptop sleeve, built for daily commuting wear and tear.',9500,null,100,10,'1 Piece','piece',1,'sinomart-bag-10',false,false,false);

-- ===== MAKEUP (beauty-personal-care) =====
select admin_seed_product('Matte Liquid Lipstick Set (6 Shades)','MUP-01','zaron',array['makeup'],'makeup','Long-wear liquid lipsticks in versatile shades.','A set of six long-wearing matte liquid lipsticks in versatile everyday-to-bold shades, formulated to resist fading through the day.',9500,11500,150,15,'1 Set of 6','set',6,'sinomart-mup-01',true,true,true);
select admin_seed_product('Full Coverage Liquid Foundation','MUP-02','fenty-beauty',array['makeup'],'makeup','Buildable foundation for an even complexion.','A buildable liquid foundation offering full coverage while maintaining a natural finish, suited to a range of skin tones.',12500,15000,110,10,'1 Piece','piece',1,'sinomart-mup-02',true,false,true);
select admin_seed_product('Eyeshadow Palette (18 Shades)','MUP-03','zaron',array['makeup'],'makeup','Versatile matte and shimmer eyeshadow palette.','An 18-shade eyeshadow palette combining matte and shimmer finishes, giving enough range for both everyday and dramatic looks.',8500,10000,130,12,'1 Piece','piece',1,'sinomart-mup-03',false,false,true);
select admin_seed_product('Waterproof Mascara','MUP-04','zaron',array['makeup'],'makeup','Smudge-resistant mascara for all-day wear.','A waterproof, smudge-resistant mascara that lengthens and volumizes lashes without flaking through a long day.',4500,null,190,16,'1 Piece','piece',1,'sinomart-mup-04',false,false,false);
select admin_seed_product('Setting Powder (Translucent)','MUP-05','fenty-beauty',array['makeup'],'makeup','Locks makeup in place with a soft-focus finish.','A translucent setting powder that locks foundation and concealer in place while softening the look of pores and fine lines.',7500,9000,140,12,'1 Piece','piece',1,'sinomart-mup-05',false,false,false);
select admin_seed_product('Eyebrow Pencil & Gel Duo','MUP-06','zaron',array['makeup'],'makeup','Fills and sets brows in one product.','A dual-ended brow product combining a fine-tip pencil for filling with a clear gel for setting brows in place.',3800,4500,170,15,'1 Piece','piece',1,'sinomart-mup-06',false,false,false);
select admin_seed_product('Makeup Brush Set (12 Piece)','MUP-07','sinomart-essentials',array['makeup','beauty-tools'],'makeup','Complete brush set with a travel case.','A twelve-piece makeup brush set covering face and eye application, packaged with a zip travel case.',7500,9000,120,10,'1 Set of 12','set',12,'sinomart-mup-07',true,false,false);
select admin_seed_product('Concealer Stick (Full Coverage)','MUP-08','fenty-beauty',array['makeup'],'makeup','Creamy concealer for blemishes and dark circles.','A creamy, full-coverage concealer stick that blends easily, formulated to cover blemishes and under-eye dark circles.',5500,null,160,14,'1 Piece','piece',1,'sinomart-mup-08',false,false,false);
select admin_seed_product('Makeup Setting Spray 100ml','MUP-09','zaron',array['makeup'],'makeup','Final-step spray for longer-lasting makeup.','A fine-mist setting spray applied as the final makeup step, helping the full look last through heat and humidity.',5200,6200,145,12,'1 Piece','piece',1,'sinomart-mup-09',false,false,false);
select admin_seed_product('Highlighter & Blush Duo Palette','MUP-10','fenty-beauty',array['makeup'],'makeup','Cream-to-powder duo for a natural glow.','A two-in-one highlighter and blush palette formulated for a natural, lit-from-within glow with buildable pigment.',6800,8000,100,10,'1 Piece','piece',1,'sinomart-mup-10',false,true,false);

-- ===== BABY CARE (kids-baby-toys) =====
select admin_seed_product('Baby Diapers (Size 3, Pack of 50)','BBC-01','pampers',array['baby-care'],'baby-care','Soft, absorbent diapers for daily use.','A 50-count pack of size 3 diapers with a soft absorbent core, designed to keep babies dry through extended wear.',9500,11000,220,20,'1 Pack of 50','pack',50,'sinomart-bbc-01',true,false,true);
select admin_seed_product('Baby Wipes (Fragrance-Free, Pack of 80)','BBC-02','pampers',array['baby-care'],'baby-care','Gentle wipes safe for sensitive skin.','An 80-count pack of fragrance-free baby wipes, formulated to be gentle on sensitive newborn skin.',3500,4200,260,20,'1 Pack of 80','pack',80,'sinomart-bbc-02',false,false,true);
select admin_seed_product('Baby Bath Tub with Support Sling','BBC-03','chelino',array['baby-care'],'baby-care','Ergonomic tub for safe newborn bathing.','A contoured baby bath tub with a built-in mesh support sling, keeping newborns securely positioned during bath time.',9500,11000,80,8,'1 Piece','piece',1,'sinomart-bbc-03',false,true,false);
select admin_seed_product('Baby Feeding Bottle Set (3 Piece)','BBC-04','chelino',array['baby-care'],'baby-care','Anti-colic bottles in graduated sizes.','A three-bottle set with anti-colic venting valves, in graduated sizes suited to different feeding stages.',7500,9000,120,10,'1 Set of 3','set',3,'sinomart-bbc-04',false,false,false);
select admin_seed_product('Baby Nail Care Kit','BBC-05','chelino',array['baby-care'],'baby-care','Safe grooming tools sized for tiny hands.','A gentle nail-care kit with rounded-tip scissors and a soft-grip file, designed specifically for a newborn''s tiny nails.',3200,null,150,12,'1 Set','set',1,'sinomart-bbc-05',false,false,false);
select admin_seed_product('Baby Formula Milk (Stage 1, 900g)','BBC-06','sinomart-essentials',array['baby-care'],'baby-care','Nutritionally balanced formula for infants.','A stage 1 infant formula milk powder formulated to support balanced nutrition from birth, in a 900g tin.',12500,null,140,15,'1 Tin','piece',1,'sinomart-bbc-06',false,false,true);
select admin_seed_product('Baby Diaper Rash Cream 100g','BBC-07','sinomart-essentials',array['baby-care'],'baby-care','Soothing barrier cream for diaper rash.','A protective barrier cream that soothes and helps prevent diaper rash, suitable for use at every diaper change.',3000,3600,175,15,'1 Piece','piece',1,'sinomart-bbc-07',false,false,false);
select admin_seed_product('Baby Health & Grooming Kit (10 Piece)','BBC-08','chelino',array['baby-care'],'baby-care','Complete kit for early newborn care.','A ten-piece newborn care kit including a thermometer, nasal aspirator, and grooming tools in a carry case.',8500,10000,95,10,'1 Set','set',1,'sinomart-bbc-08',true,false,false);
select admin_seed_product('Baby Bibs (Waterproof, Pack of 4)','BBC-09','chelino',array['baby-care'],'baby-care','Easy-wipe bibs for messy mealtimes.','Four waterproof, easy-wipe bibs with adjustable neck closures, built to handle messy self-feeding stages.',3500,null,160,14,'1 Pack of 4','pack',4,'sinomart-bbc-09',false,false,false);
select admin_seed_product('Baby Powder (Talc-Free) 200g','BBC-10','sinomart-essentials',array['baby-care'],'baby-care','Gentle powder to keep skin dry and fresh.','A talc-free baby powder that helps keep skin dry and comfortable, formulated to be gentle on delicate newborn skin.',2200,2600,190,16,'1 Piece','piece',1,'sinomart-bbc-10',false,false,false);
