-- =====================================================================================
-- 029_seed_products_part9.sql — Sports & Outdoor: Fitness
--                                Office & School: Stationery
--                                Pet Supplies: Pet Food & Treats
-- =====================================================================================

-- ===== FITNESS (sports-outdoor) =====
select admin_seed_product('Yoga Mat with Carry Strap (6mm)','FIT-01','sinomart-essentials',array['fitness'],'fitness','Cushioned mat for yoga and floor workouts.','A 6mm non-slip yoga mat with a textured surface for grip, bundled with a carry strap for easy transport to class or the gym.',7500,9000,150,15,'1 Piece','piece',1,'sinomart-fit-01',true,true,true);
select admin_seed_product('Adjustable Dumbbell Set (2x10kg)','FIT-02','sinomart-essentials',array['fitness'],'fitness','Space-saving dumbbells for home workouts.','A pair of adjustable dumbbells with removable plates, letting users change resistance from 2kg up to 10kg per hand.',22500,26000,60,8,'1 Set of 2','set',2,'sinomart-fit-02',true,false,true);
select admin_seed_product('Resistance Bands Set (5 Levels)','FIT-03','sinomart-essentials',array['fitness'],'fitness','Latex bands for strength and mobility training.','A set of five latex resistance bands in graduated strengths, useful for strength training, mobility work, or physiotherapy.',5500,6500,180,15,'1 Set of 5','set',5,'sinomart-fit-03',false,false,true);
select admin_seed_product('Skipping Rope (Adjustable Length)','FIT-04','sinomart-essentials',array['fitness'],'fitness','Ball-bearing rope for smooth, fast turns.','An adjustable-length skipping rope with ball-bearing handles, giving smooth and fast rope turns for cardio workouts.',3200,null,220,18,'1 Piece','piece',1,'sinomart-fit-04',false,false,false);
select admin_seed_product('Foam Roller for Muscle Recovery','FIT-05','sinomart-essentials',array['fitness'],'fitness','Firm roller to relieve muscle tightness.','A firm-density foam roller used for self-myofascial release, helping relieve muscle tightness after workouts.',6500,7800,110,10,'1 Piece','piece',1,'sinomart-fit-05',false,false,false);
select admin_seed_product('Ab Wheel Roller','FIT-06','sinomart-essentials',array['fitness'],'fitness','Compact core-strengthening equipment.','A dual-wheel ab roller with cushioned handles, targeting core strength through controlled rolling movements.',4500,5200,130,12,'1 Piece','piece',1,'sinomart-fit-06',false,false,false);
select admin_seed_product('Weighted Vest (5kg)','FIT-07','sinomart-essentials',array['fitness'],'fitness','Adjustable vest to intensify bodyweight training.','A 5kg adjustable weighted vest that adds resistance to running, walking, or bodyweight exercises for increased intensity.',13500,15500,55,8,'1 Piece','piece',1,'sinomart-fit-07',false,false,false);
select admin_seed_product('Fitness Gym Bag with Shoe Compartment','FIT-08','sinomart-essentials',array['fitness','bags'],'fitness','Duffel bag with a separate shoe pocket.','A durable gym duffel bag with a ventilated separate compartment for shoes, keeping sweaty kit away from clean clothes.',8500,10000,95,10,'1 Piece','piece',1,'sinomart-fit-08',false,false,false);
select admin_seed_product('Push-Up Bars (Pair)','FIT-09','sinomart-essentials',array['fitness'],'fitness','Ergonomic bars for deeper push-up range.','A pair of push-up bars with a non-slip rubber base, allowing a deeper range of motion and reduced wrist strain.',4000,null,150,12,'1 Pair','pair',1,'sinomart-fit-09',false,false,false);
select admin_seed_product('Digital Body Weighing Scale','FIT-10','sinomart-essentials',array['fitness'],'fitness','Precise digital scale for tracking progress.','A digital bathroom scale with a large, easy-read display, giving precise weight readings to track fitness progress.',7500,9000,105,10,'1 Piece','piece',1,'sinomart-fit-10',false,false,false);

-- ===== STATIONERY (office-school) =====
select admin_seed_product('Ballpoint Pens (Pack of 20, Blue)','STA-01','sinomart-essentials',array['stationery'],'stationery','Smooth-writing everyday pens.','A pack of twenty smooth-writing blue ballpoint pens, a reliable everyday choice for school, office, or general use.',3000,3600,260,20,'1 Pack of 20','pack',20,'sinomart-sta-01',true,false,true);
select admin_seed_product('A5 Hardcover Notebook','STA-02','sinomart-essentials',array['stationery'],'stationery','Durable notebook with lined pages.','An A5 hardcover notebook with 200 lined pages and a ribbon bookmark, suited to journaling, notes, or planning.',3500,4200,220,18,'1 Piece','piece',1,'sinomart-sta-02',false,true,false);
select admin_seed_product('Stapler with Staples (Standard)','STA-03','sinomart-essentials',array['stationery','office-supplies'],'stationery','Reliable stapler for everyday document use.','A standard desktop stapler with a full box of staples included, suited to everyday document binding tasks.',3200,null,180,15,'1 Piece','piece',1,'sinomart-sta-03',false,false,false);
select admin_seed_product('Sticky Note Cube (400 Sheets)','STA-04','sinomart-essentials',array['stationery'],'stationery','Compact cube of assorted sticky notes.','A 400-sheet sticky note cube in assorted pastel colours, a compact desk essential for quick reminders.',2200,2600,240,18,'1 Piece','piece',1,'sinomart-sta-04',false,false,false);
select admin_seed_product('Wooden HB Pencils (Pack of 12)','STA-05','sinomart-essentials',array['stationery'],'stationery','Classic pencils with attached erasers.','Twelve HB wooden pencils with attached erasers, pre-sharpened and ready for everyday writing or exam use.',2000,null,300,25,'1 Pack of 12','pack',12,'sinomart-sta-05',false,false,true);
select admin_seed_product('Clipboard with Storage (A4)','STA-06','sinomart-essentials',array['stationery','office-supplies'],'stationery','Clipboard with a hidden storage compartment.','An A4 clipboard with a low-profile clip and a hidden storage compartment beneath the writing surface for loose papers.',3800,4500,150,12,'1 Piece','piece',1,'sinomart-sta-06',false,false,false);
select admin_seed_product('Glue Stick Multi-Pack (6 Piece)','STA-07','sinomart-essentials',array['stationery'],'stationery','Non-toxic glue sticks for paper crafts.','Six non-toxic glue sticks suited to paper crafts, school projects, and general office use.',2500,null,200,16,'1 Pack of 6','pack',6,'sinomart-sta-07',false,false,false);
select admin_seed_product('Desk Organizer Pen Cup (Mesh)','STA-08','sinomart-essentials',array['stationery'],'stationery','Wire mesh cup to keep pens tidy.','A wire mesh pen cup that keeps pens, pencils, and small tools upright and easy to grab from a desk.',2500,3000,190,15,'1 Piece','piece',1,'sinomart-sta-08',false,false,false);
select admin_seed_product('A3 Poster Board (Pack of 10, Assorted Colors)','STA-09','sinomart-essentials',array['stationery','educational-materials'],'stationery','Sturdy boards for school projects and displays.','Ten A3 poster boards in assorted bright colours, a sturdy base for school projects, charts, and classroom displays.',4500,5200,130,10,'1 Pack of 10','pack',10,'sinomart-sta-09',false,false,false);
select admin_seed_product('Rubber Erasers (Pack of 10)','STA-10','sinomart-essentials',array['stationery'],'stationery','Clean-lift erasers for pencil work.','Ten soft rubber erasers that lift pencil marks cleanly without smudging or tearing paper.',1800,null,280,20,'1 Pack of 10','pack',10,'sinomart-sta-10',false,false,false);

-- ===== PET FOOD & TREATS (pet-supplies) =====
select admin_seed_product('Adult Dog Dry Food 3kg','PFT-01','sinomart-essentials',array['pet-food-treats'],'pet-food-treats','Balanced kibble for everyday dog nutrition.','A 3kg bag of balanced dry dog food formulated with protein and essential nutrients to support everyday health for adult dogs.',9500,11000,140,12,'1 Bag','piece',1,'sinomart-pft-01',true,false,true);
select admin_seed_product('Adult Cat Dry Food 2kg','PFT-02','sinomart-essentials',array['pet-food-treats'],'pet-food-treats','Complete nutrition for indoor cats.','A 2kg bag of complete dry cat food formulated for indoor adult cats, supporting healthy digestion and coat condition.',7500,8800,130,12,'1 Bag','piece',1,'sinomart-pft-02',false,false,true);
select admin_seed_product('Dog Dental Chew Treats (Pack of 10)','PFT-03','sinomart-essentials',array['pet-food-treats'],'pet-food-treats','Chew treats that help support dental health.','Ten dental chew treats formulated to help reduce plaque buildup while dogs enjoy a rewarding chew.',5500,6500,100,10,'1 Pack of 10','pack',10,'sinomart-pft-03',false,false,false);
select admin_seed_product('Cat Treats (Salmon Flavor, 100g)','PFT-04','sinomart-essentials',array['pet-food-treats'],'pet-food-treats','Bite-sized salmon-flavored cat treats.','Bite-sized, salmon-flavored cat treats useful for training rewards or occasional snacking.',2800,3200,150,12,'1 Piece','piece',1,'sinomart-pft-04',false,false,false);
select admin_seed_product('Puppy Starter Dry Food 1.5kg','PFT-05','sinomart-essentials',array['pet-food-treats'],'pet-food-treats','Nutrient-dense food for growing puppies.','A 1.5kg bag of nutrient-dense puppy food, formulated to support healthy growth in the first year.',6800,8000,90,8,'1 Bag','piece',1,'sinomart-pft-05',false,true,false);
select admin_seed_product('Rabbit & Small Pet Pellet Food 1kg','PFT-06','sinomart-essentials',array['pet-food-treats'],'pet-food-treats','Balanced pellets for rabbits and guinea pigs.','A 1kg bag of balanced pellet food suited to rabbits, guinea pigs, and other small herbivorous pets.',3500,null,80,8,'1 Bag','piece',1,'sinomart-pft-06',false,false,false);
select admin_seed_product('Bird Seed Mix 1kg','PFT-07','sinomart-essentials',array['pet-food-treats'],'pet-food-treats','Varied seed blend for pet birds.','A 1kg mixed seed blend formulated for common pet bird species, supporting varied daily nutrition.',3200,3800,75,8,'1 Bag','piece',1,'sinomart-pft-07',false,false,false);
select admin_seed_product('Dog Training Treat Pouch Kit','PFT-08','sinomart-essentials',array['pet-food-treats','pet-accessories'],'pet-food-treats','Treats and pouch bundled for training sessions.','A bundled kit combining a clip-on treat pouch with a bag of small training treats, useful for obedience sessions.',6500,7500,60,8,'1 Set','set',1,'sinomart-pft-08',false,false,false);
select admin_seed_product('Senior Dog Dry Food (Joint Support) 3kg','PFT-09','sinomart-essentials',array['pet-food-treats'],'pet-food-treats','Formulated food supporting aging joints.','A 3kg bag of senior-formulated dry dog food including ingredients aimed at supporting joint health in older dogs.',10500,12000,55,6,'1 Bag','piece',1,'sinomart-pft-09',false,false,false);
select admin_seed_product('Cat Wet Food Pouches (Pack of 12)','PFT-10','sinomart-essentials',array['pet-food-treats'],'pet-food-treats','Convenient wet food pouches for daily variety.','Twelve single-serve wet food pouches, adding moisture and variety to a cat''s regular dry-food diet.',6500,7500,95,10,'1 Pack of 12','pack',12,'sinomart-pft-10',false,false,false);
