-- =====================================================================================
-- 030_seed_products_part10.sql — Travel & Luggage: Travel Bags
--                                 Groceries & Everyday Essentials: Beverages
--                                 Tools & Hardware: Hardware
-- =====================================================================================

-- ===== TRAVEL BAGS (travel-luggage) =====
select admin_seed_product('Weekend Duffel Travel Bag','TRB-01','sinomart-essentials',array['travel-bags'],'travel-bags','Spacious duffel for short getaways.','A durable weekend duffel bag with a padded shoulder strap and shoe compartment, sized for a two-to-three day trip.',12500,15000,100,10,'1 Piece','piece',1,'sinomart-trb-01',true,true,true);
select admin_seed_product('Foldable Travel Duffel Bag','TRB-02','sinomart-essentials',array['travel-bags'],'travel-bags','Packs flat when not in use.','A lightweight duffel bag that folds flat into its own pouch, useful as a spare bag for extra luggage on the return trip.',6500,7800,140,12,'1 Piece','piece',1,'sinomart-trb-02',false,false,false);
select admin_seed_product('Underseat Cabin Travel Bag','TRB-03','sinomart-essentials',array['travel-bags'],'travel-bags','Fits under most airline seats.','A compact travel bag sized to fit under most airline seats, ideal as a personal item alongside a cabin suitcase.',9500,11000,90,10,'1 Piece','piece',1,'sinomart-trb-03',false,false,false);
select admin_seed_product('Waterproof Dry Bag 20L','TRB-04','sinomart-essentials',array['travel-bags','camping-outdoor'],'travel-bags','Keeps contents dry for beach and boat trips.','A roll-top waterproof dry bag with a 20-litre capacity, protecting electronics and clothing during beach, boat, or rainy travel.',6500,null,75,8,'1 Piece','piece',1,'sinomart-trb-04',false,false,false);
select admin_seed_product('Toiletry Travel Bag (Hanging)','TRB-05','sinomart-essentials',array['travel-bags','travel-accessories'],'travel-bags','Hangs for easy access in hotel bathrooms.','A hanging toiletry bag with multiple compartments and a sturdy hook, keeping toiletries organized in hotel bathrooms.',5500,6500,130,12,'1 Piece','piece',1,'sinomart-trb-05',false,false,false);
select admin_seed_product('Garment Travel Bag (Foldable)','TRB-06','sinomart-essentials',array['travel-bags'],'travel-bags','Keeps suits and dresses wrinkle-free.','A foldable garment bag that keeps suits, dresses, and formal wear wrinkle-free while travelling.',7500,9000,60,8,'1 Piece','piece',1,'sinomart-trb-06',false,false,false);
select admin_seed_product('Travel Backpack with Anti-Theft Zip','TRB-07','sinomart-essentials',array['travel-bags','travel-backpacks'],'travel-bags','Secure backpack for city exploring.','A travel backpack with hidden anti-theft zippers and a padded laptop sleeve, suited to city exploring and day trips.',13500,16000,85,8,'1 Piece','piece',1,'sinomart-trb-07',false,false,true);
select admin_seed_product('Compression Packing Duffel','TRB-08','sinomart-essentials',array['travel-bags'],'travel-bags','Compression straps maximize packing space.','A duffel bag with internal compression straps, helping fit more into the same amount of luggage space.',9500,11000,70,8,'1 Piece','piece',1,'sinomart-trb-08',false,false,false);
select admin_seed_product('Shoe Storage Travel Pouches (Set of 2)','TRB-09','sinomart-essentials',array['travel-bags','travel-organizers'],'travel-bags','Keeps shoes separate from clean clothing.','Two drawstring shoe pouches that keep footwear separated from clean clothing inside a suitcase or duffel.',3200,3800,150,12,'1 Set of 2','set',2,'sinomart-trb-09',false,false,false);
select admin_seed_product('Rolling Travel Duffel with Wheels','TRB-10','sinomart-essentials',array['travel-bags'],'travel-bags','Wheeled duffel for heavier packing loads.','A wheeled duffel bag combining suitcase-style rolling with the flexibility of a soft-sided duffel, for heavier loads.',16500,19000,55,6,'1 Piece','piece',1,'sinomart-trb-10',false,false,false);

-- ===== BEVERAGES (groceries-essentials) =====
select admin_seed_product('Bottled Drinking Water (Pack of 12, 75cl)','BEV-01','sinomart-essentials',array['beverages'],'beverages','Everyday hydration pack for home or office.','A twelve-bottle pack of purified drinking water, a household and office staple for everyday hydration.',3500,4000,320,25,'1 Pack of 12','pack',12,'sinomart-bev-01',false,false,true);
select admin_seed_product('Instant Coffee 200g Jar','BEV-02','sinomart-essentials',array['beverages'],'beverages','Rich instant coffee for a quick brew.','A 200g jar of rich instant coffee granules, dissolving quickly for a smooth cup without brewing equipment.',5500,6200,180,15,'1 Piece','piece',1,'sinomart-bev-02',true,false,true);
select admin_seed_product('Assorted Fruit Juice Multipack (6 x 1L)','BEV-03','sinomart-essentials',array['beverages'],'beverages','Six assorted juice cartons for the fridge.','A multipack of six 1-litre fruit juice cartons in assorted flavours, convenient for stocking the fridge.',7500,8500,150,12,'1 Pack of 6','pack',6,'sinomart-bev-03',false,false,false);
select admin_seed_product('Green Tea Bags (Pack of 100)','BEV-04','sinomart-essentials',array['beverages'],'beverages','Everyday green tea for hot or iced brewing.','A 100-count pack of green tea bags, suited to daily hot brewing or as a base for iced tea.',3800,4500,190,16,'1 Pack of 100','pack',100,'sinomart-bev-04',false,false,false);
select admin_seed_product('Powdered Milk Drink 400g','BEV-05','sinomart-essentials',array['beverages'],'beverages','Everyday powdered milk for tea and cereal.','A 400g tin of powdered milk drink, a household staple for tea, cereal, and general cooking use.',4200,null,220,18,'1 Piece','piece',1,'sinomart-bev-05',false,false,true);
select admin_seed_product('Malt Drink (Non-Alcoholic, Pack of 6)','BEV-06','sinomart-essentials',array['beverages'],'beverages','Nutritious malt drink cans, six-pack.','A six-can pack of non-alcoholic malt drink, a popular everyday Nigerian household beverage.',3200,3800,200,16,'1 Pack of 6','pack',6,'sinomart-bev-06',false,false,false);
select admin_seed_product('Ground Coffee Beans 250g','BEV-07','sinomart-essentials',array['beverages'],'beverages','Freshly ground beans for filter or French press.','A 250g bag of ground coffee beans suited to filter machines or a French press, offering a fuller-bodied brew than instant coffee.',6500,7500,110,10,'1 Piece','piece',1,'sinomart-bev-07',false,true,false);
select admin_seed_product('Zobo Drink Mix (Hibiscus) 500g','BEV-08','sinomart-essentials',array['beverages'],'beverages','Dried hibiscus for a refreshing local drink.','A 500g pack of dried hibiscus (zobo) leaves for preparing a refreshing, naturally tart chilled beverage at home.',2500,null,140,12,'1 Piece','piece',1,'sinomart-bev-08',false,false,false);
select admin_seed_product('Sparkling Soft Drink Multipack (6 Cans)','BEV-09','sinomart-essentials',array['beverages'],'beverages','Six-pack of classic carbonated soft drinks.','A six-can multipack of classic carbonated soft drinks, suited to gatherings or everyday fridge stocking.',3000,3500,230,18,'1 Pack of 6','pack',6,'sinomart-bev-09',false,false,false);
select admin_seed_product('Energy Drink (Pack of 4)','BEV-10','sinomart-essentials',array['beverages'],'beverages','Caffeinated energy drink four-pack.','A four-can pack of caffeinated energy drink, useful for long study sessions, road trips, or an afternoon pick-me-up.',3500,null,160,14,'1 Pack of 4','pack',4,'sinomart-bev-10',false,false,false);

-- ===== HARDWARE (tools-hardware) =====
select admin_seed_product('Assorted Wood Screws (Box of 200)','HDW-01','sinomart-essentials',array['hardware'],'hardware','Mixed-size screws for general repairs.','A 200-piece box of assorted wood screws in varied lengths, useful for general household repairs and small carpentry projects.',3500,4200,160,14,'1 Box of 200','box',200,'sinomart-hdw-01',false,false,true);
select admin_seed_product('Padlock with Keys (Heavy-Duty)','HDW-02','sinomart-essentials',array['hardware'],'hardware','Weather-resistant padlock for gates and sheds.','A heavy-duty, weather-resistant padlock supplied with two keys, suited to gates, sheds, and storage lockers.',3200,3800,150,12,'1 Piece','piece',1,'sinomart-hdw-02',false,false,false);
select admin_seed_product('Door Hinges (Pack of 4)','HDW-03','sinomart-essentials',array['hardware'],'hardware','Standard hinges for interior doors.','Four standard steel door hinges with mounting screws included, suited to interior door installation or replacement.',4500,null,110,10,'1 Pack of 4','pack',4,'sinomart-hdw-03',false,false,false);
select admin_seed_product('Cabinet Handles & Knobs (Pack of 10)','HDW-04','sinomart-essentials',array['hardware'],'hardware','Matching handles to refresh cabinets.','Ten matching cabinet handles in a brushed metal finish, an easy way to refresh kitchen or wardrobe cabinets.',5500,6500,130,12,'1 Pack of 10','pack',10,'sinomart-hdw-04',false,false,false);
select admin_seed_product('Anchor Bolts & Wall Plugs Kit','HDW-05','sinomart-essentials',array['hardware'],'hardware','Wall-fixing kit for shelves and mounts.','An assorted kit of wall plugs and anchor bolts, suited to mounting shelves, TV brackets, and other wall fixtures securely.',3800,4500,140,12,'1 Kit','set',1,'sinomart-hdw-05',false,false,false);
select admin_seed_product('Chain Lock Set (2m)','HDW-06','sinomart-essentials',array['hardware'],'hardware','Vinyl-coated chain for securing gates or items.','A 2-metre vinyl-coated steel chain with a padlock, useful for securing gates, generators, or outdoor equipment.',6500,7500,85,8,'1 Set','set',1,'sinomart-hdw-06',false,false,false);
select admin_seed_product('Door Stopper (Pack of 4)','HDW-07','sinomart-essentials',array['hardware'],'hardware','Rubber stoppers to protect walls and doors.','Four rubber door stoppers that protect walls from damage caused by doors swinging open too far.',2000,null,190,16,'1 Pack of 4','pack',4,'sinomart-hdw-07',false,false,false);
select admin_seed_product('Sliding Door Track Roller Set','HDW-08','sinomart-essentials',array['hardware'],'hardware','Replacement rollers for sliding wardrobe doors.','A replacement roller set for sliding wardrobe or cabinet doors, restoring smooth gliding motion.',4200,5000,70,8,'1 Set','set',1,'sinomart-hdw-08',false,false,false);
select admin_seed_product('Picture Hanging Kit (Assorted Sizes)','HDW-09','sinomart-essentials',array['hardware','home-decor'],'hardware','Complete kit for hanging frames and mirrors.','An assorted picture-hanging kit with hooks, nails, and wire rated for various frame weights.',3000,3600,160,14,'1 Kit','set',1,'sinomart-hdw-09',false,false,false);
select admin_seed_product('Rubber Furniture Floor Protectors (Pack of 16)','HDW-10','sinomart-essentials',array['hardware','furniture'],'hardware','Protects floors from furniture scratches.','Sixteen self-adhesive rubber floor protectors, fitted under chair and table legs to prevent scratches on tiled or wooden floors.',2500,null,200,16,'1 Pack of 16','pack',16,'sinomart-hdw-10',false,false,false);
